// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/go-chi/chi/v5"
)

const (
	AdminAuthScopes = "adminAuth.Scopes"
	BasicScopes     = "basic.Scopes"
)

// Defines values for NetworkInfoChainId.
const (
	NetworkInfoChainIdMAINNET  NetworkInfoChainId = "MAINNET"
	NetworkInfoChainIdTESTNET1 NetworkInfoChainId = "TESTNET1"
	NetworkInfoChainIdTESTNET2 NetworkInfoChainId = "TESTNET2"
)

// Defines values for NetworkInfoConsensus.
const (
	DPOS NetworkInfoConsensus = "dPOS"
	POA  NetworkInfoConsensus = "POA"
	POS  NetworkInfoConsensus = "POS"
)

// Defines values for PeerStatus.
const (
	CANDIDATE    PeerStatus = "CANDIDATE"
	CONNECTED    PeerStatus = "CONNECTED"
	NOTCONNECTED PeerStatus = "NOT_CONNECTED"
)

// Defines values for PeerTrustLevel.
const (
	ORDINARY  PeerTrustLevel = "ORDINARY"
	SYSTEM    PeerTrustLevel = "SYSTEM"
	UNTRUSTED PeerTrustLevel = "UNTRUSTED"
)

// Defines values for UnifiedTransactionChainId.
const (
	UnifiedTransactionChainIdMAINNET  UnifiedTransactionChainId = "MAINNET"
	UnifiedTransactionChainIdTESTNET1 UnifiedTransactionChainId = "TESTNET1"
	UnifiedTransactionChainIdTESTNET2 UnifiedTransactionChainId = "TESTNET2"
)

// Defines values for UnifiedTransactionStatus.
const (
	FAILED               UnifiedTransactionStatus = "FAILED"
	NOTEXECUTED          UnifiedTransactionStatus = "NOT_EXECUTED"
	SUCCESSFULLYEXECUTED UnifiedTransactionStatus = "SUCCESSFULLY_EXECUTED"
)

// ABI for contract (List of contract functions/constructors to read/write state)
type ABI struct {
	// Content of the contract ABI, json scheme for inputs of constructor, input/outputs for read and write functions
	Content *string `json:"content,omitempty"`
}

// Indicates result of ABI save operation
type ABISaveResponse struct {
	Success *bool `json:"success,omitempty"`
}

// User's account identified by id and public key to hold native coins on balance, sign and send transactions
type Account struct {
	// Amount of the native coins held by the acount in float format
	Balance *string `json:"balance,omitempty"`

	// Time of the account creation UTC (first outgoing transaction confirmation)
	Created *time.Time `json:"created,omitempty"`

	// Unique identifier of the account derived from its public key encoded hex format (Ethereum-like)
	Id *string `json:"id,omitempty"`

	// Number of transactions sent by account and confirmed in LunaOne network. This number is used to order transactions in mempool and confirm them from lesser nonce to higher without allowing gaps. (tx1-nonce-1, tx2-nonce-3 - only tx1 will be confirmed until the tx3-nonc-2 will be sent to allow the confirmation of tx3)
	Nonce *int64 `json:"nonce,omitempty"`

	// Public key for EC (elliptic curve Ed25519) cryptography operations (verify the signature of the transaction, signed by this account's private key). Key is encoded in hexadecimal format (Ed25519 compressed format with only X point). Public key is getting published into the LunaOne network via first outgoing transaction
	PublicKey *string `json:"publicKey,omitempty"`
}

// List of sorted user accounts
type Accounts struct {
	Accounts *[]Account `json:"accounts,omitempty"`
}

// General API error returned when any error occurred during performing API call
type ApiError struct {
	// Reason of the occurred error or its content
	Error *string `json:"error,omitempty"`
}

// Object composed of sender/recipient addresses, transferred amount and call_data (method+params, contract_code+contructor_params) intended for smart contract execution with no formed transaction
type CallMessage struct {
	// Amount of neutrino (minimal value unit) transferred via this call from sender to recipient. Can be zero
	Amount *string `json:"amount,omitempty"`

	// smart contract code + constructor parameters for contract publishing transaction or call_data (smart contract method's signature to call with encoded paramaters)
	Data *string `json:"data,omitempty"`

	// Ethereum-based address of the contract to call (required)
	Recipient *string `json:"recipient,omitempty"`

	// Ethereum-based address of the sending account (optional)
	Sender *string `json:"sender,omitempty"`
}

// Result of the method invocation, can not be empty, if contract address does not exist return c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470. Result is a code hash and a contract code.
type Code struct {
	// Result is a contract code encoded in hex, if contract address does not exist return empty string.
	CodeContract *string `json:"codeContract,omitempty"`

	// Return  codeHash if contract by given address exist, if contract address does not exist return c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470.
	CodeHash *string `json:"codeHash,omitempty"`
}

// ContractMethodCallResult defines model for ContractMethodCallResult.
type ContractMethodCallResult struct {
	// Result of the method invocation, can be empty when method return nothing. Result is a serialized output of the received value/values from called method. Result serialization rules are defined by future implementation
	Result *string `json:"result,omitempty"`
}

// Result of the transaction fuel consumption estimation, indicate
type FuelEstimationResult struct {
	// Status of mocked transaction execution (for estimation) denoting either successful execution ('SUCCESS') or failed (with possible error cause) - any other output
	ExecutionStatus *string `json:"executionStatus,omitempty"`

	// Approximate amount of fuel units to be used for transaction execution (depends on current node's state). Recommended to add at least 5% bonus to it before signing and broadcasting transaction
	FuelEstimate *int64 `json:"fuelEstimate,omitempty"`

	// Hash of the transaction (Keccak-256) prefixed with '0x'
	TxHash *string `json:"txHash,omitempty"`
}

// Smart contract event log
type Log struct {
	// Address of the contract for which this event log was created
	Address *string `json:"address,omitempty"`

	// Actual data content of the log corresponding to all non-indexed fields of event (all fields excluding topics combined together)
	Data *string `json:"data,omitempty"`

	// Number of the pinning transaction where this log appearerd during contract execution
	PinTxNumber *string `json:"pinTxNumber,omitempty"`

	// Topics for this logged event (indexed evet fields, first is event signature KECCAK_256 of string event name)
	Topics *[]string `json:"topics,omitempty"`

	// Hash of the transaction that created this log
	TransactionHash *string `json:"transactionHash,omitempty"`
}

// List of logs from smart contract
type LogsResponse struct {
	// Array of sorted logs
	Logs *[]Log `json:"logs,omitempty"`
}

// General network information the node is connected to
type NetworkInfo struct {
	// Id of the network whereto transaction is sent and was confirmed
	ChainId *NetworkInfoChainId `json:"chainId,omitempty"`

	// Type of the consensus (generator/validator choosing strategy) chosen for the LunaOne network
	Consensus *NetworkInfoConsensus `json:"consensus,omitempty"`

	// Current number of the blocks on top of genesis block
	Height *int64 `json:"height,omitempty"`
}

// Id of the network whereto transaction is sent and was confirmed
type NetworkInfoChainId string

// Type of the consensus (generator/validator choosing strategy) chosen for the LunaOne network
type NetworkInfoConsensus string

// Information about node connected to the LunaOne network which is responsible for transaction propagation, validation and confirmation
type Peer struct {
	// Time when the node was firstly accepted into the network to validate/confirm transactions (UTC)
	EnrolledAt *time.Time `json:"enrolledAt,omitempty"`

	// Domain name or IP (v4/v6) with optional port value appended whereto the P2P requests can be sent and properly responded by this node
	Hostname *string `json:"hostname,omitempty"`

	// Cryptographically generated id of the node from its public key. Format may be changed
	Id *string `json:"id,omitempty"`

	// Time of the last communication with the node UTC
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`

	// EC public key of the node to verify signed messages from this node (SECP256K1) encoded via DER from ASN1
	PublicKey *string `json:"publicKey,omitempty"`

	// Reliability of the node showing a percent of successfully completed job in the network
	Reputation *string `json:"reputation,omitempty"`

	// Status of the node's connection to the network
	Status *PeerStatus `json:"status,omitempty"`

	// Level of the trust showing how are the results received from node can be trusted. SYSTEM node's responses are trusted the most, ORDINARY node's results can be verified with other ORDINARY nodes, UNTRUSTED are better to be verified against SYSTEM nodes or better off not actually request data from UNTRUSTED nodes
	TrustLevel *PeerTrustLevel `json:"trustLevel,omitempty"`

	// Version of the LunaOne client launched
	Version *string `json:"version,omitempty"`
}

// Status of the node's connection to the network
type PeerStatus string

// Level of the trust showing how are the results received from node can be trusted. SYSTEM node's responses are trusted the most, ORDINARY node's results can be verified with other ORDINARY nodes, UNTRUSTED are better to be verified against SYSTEM nodes or better off not actually request data from UNTRUSTED nodes
type PeerTrustLevel string

// Return current number of pinning transaction
type PinNumber struct {
	// Latest pinning transaction number
	PinNumber *int `json:"pinNumber,omitempty"`
}

// Check this node's pubsub readiness status
type PubsubReady struct {
	Ready *bool `json:"ready,omitempty"`
}

// New signed transaction to be sent to the LunaOne network
type RawTransaction struct {
	// Signed and encoded into a the hexadecimal format transaction that must be sent into the LunaOne network and get confirmed
	EncodedTx string `json:"encodedTx"`
}

// Diagnosis information about the full node software running including versions, threads, connectivity activities
type SystemInfo struct {
	// Number of nonblocked backgroung threads performing some work
	ActiveThreads *int `json:"activeThreads,omitempty"`

	// Version of the REST API provided by the node
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Number of active db connections performing work
	DbActiveConnections *int `json:"dbActiveConnections,omitempty"`

	// Number of total db connections in a pool ready to query db
	DbTotalConnections *int `json:"dbTotalConnections,omitempty"`

	// Version of the P2P protocol used to interact with other nodes over LunaOne network
	P2pVersion *string `json:"p2pVersion,omitempty"`

	// Number of total thread currently alive under full node's process
	TotalThreads *int `json:"totalThreads,omitempty"`

	// Version of the full node software package
	Version *string `json:"version,omitempty"`
}

// Transaction execution receipt object
type TxReceipt struct {
	// Status of transaction execution denoting either successful execution ('SUCCESS') or failed (with possible error cause) - any other output
	ExecutionStatus *string `json:"executionStatus,omitempty"`

	// Amount of fuel used for transaction execution out of specified fuel limit
	FuelUsed *int64 `json:"fuelUsed,omitempty"`

	// Hash of the transaction (Keccak-256) prefixed with '0x'
	TxHash *string `json:"txHash,omitempty"`
}

// Transaction object, containing results of execution, used fuel, actual fee and prettified date, chainId, amount fields. Most of tx execution fields are absent for UnconfirmedTx
type UnifiedTransaction struct {
	// Amount of transferred tokens in minimal units (neutrinos)
	Amount *string `json:"amount,omitempty"`

	// Id of the network whereto transaction is sent
	ChainId *UnifiedTransactionChainId `json:"chainId,omitempty"`

	// Additional data bytes storing user-defined messages or smart contract's code, method call parameters. Every additional byte charges a fee
	Data *string `json:"data,omitempty"`

	// Actual fee payed for the transaction in neutrinos
	Fee *string `json:"fee,omitempty"`

	// Amount of the fuel allowed by sender's to be used at max to confirm the transaction
	FuelLimit *string `json:"fuelLimit,omitempty"`

	// Price of the every single unit of fuel used for transaction which was payed as tx fee
	FuelPrice *string `json:"fuelPrice,omitempty"`

	// Amount of fuel actually used to confirm transaction (in both failed or executed cases). For Payments the whole amount of fuel limit will be used, for contract's trasaction used amount will <=fuelLimit
	FuelUsed *string `json:"fuelUsed,omitempty"`

	// Number of the transaction sent from the sender's account (forming an increment-only sequence of unique nonces where transactions are get confirmed from lower numbers to higher without gaps), should be always zero for Payments
	Nonce *int `json:"nonce,omitempty"`

	// Pin tx number in always increasing sequence specifying that transaction was confirmed by a certain pinning tx. For unconfirmed transactions this field is empty (no associated pinning tx)
	PinTxNumber *int `json:"pinTxNumber,omitempty"`

	// Address of the recipient's account, Ethereum-like P2PKH
	Recipient *string `json:"recipient,omitempty"`

	// Address of the sender's account, Ethereum-like
	Sender *string `json:"sender,omitempty"`

	// Sender's signature done by their private key on the entire transaction
	Signature *string `json:"signature,omitempty"`

	// Status of the transaction execution, for Payment only SUCCESSFULLY_EXECUTED allowed, for contract transactions - both SUCCESSFULLY_EXECUTED/FAILED possible
	Status *UnifiedTransactionStatus `json:"status,omitempty"`

	// Details of the current transaction status, typically containing error message for smart contracts
	StatusMessage *string `json:"statusMessage,omitempty"`

	// Timestamp (UTC) when transaction is formed in format 'YYYY-MM-ddTHH:mm:ss'
	Timestamp *string `json:"timestamp,omitempty"`

	// Hash of the signed transaction (Keccak-256)
	TxHash *string `json:"txHash,omitempty"`

	// Type of the transaction (0 - Payment transaction, 1 - Publish contract transaction, 2 - Call contract transaction)
	Type *int `json:"type,omitempty"`

	// Version of the transaction structure
	Version *int `json:"version,omitempty"`
}

// Id of the network whereto transaction is sent
type UnifiedTransactionChainId string

// Status of the transaction execution, for Payment only SUCCESSFULLY_EXECUTED allowed, for contract transactions - both SUCCESSFULLY_EXECUTED/FAILED possible
type UnifiedTransactionStatus string

// List of transactions sorted by certain criteria
type UnifiedTransactions struct {
	Transactions *[]UnifiedTransaction `json:"transactions,omitempty"`
}

// PageParam defines model for pageParam.
type PageParam = int

// PageSizeParam defines model for pageSizeParam.
type PageSizeParam = int

// New signed transaction to be sent to the LunaOne network
type SendRawTransactionRequest = RawTransaction

// GetAccountsParams defines parameters for GetAccounts.
type GetAccountsParams struct {
	// Sort accounts in ascending or descending order by 'sortCriteria'
	SortOrder *GetAccountsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// Criteria to sort accounts by
	SortCriteria *GetAccountsParamsSortCriteria `form:"sortCriteria,omitempty" json:"sortCriteria,omitempty"`

	// Number of the page to be returned, default is 0 (first page)
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Size of the page returned. Typically mustn't be changed on paging through because it will be required to recalculate position of the first element = page * size
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetAccountsParamsSortOrder defines parameters for GetAccounts.
type GetAccountsParamsSortOrder string

// GetAccountsParamsSortCriteria defines parameters for GetAccounts.
type GetAccountsParamsSortCriteria string

// GetContractsContractIdParams defines parameters for GetContractsContractId.
type GetContractsContractIdParams struct {
	Params *string `form:"params,omitempty" json:"params,omitempty"`
	Sender *string `form:"sender,omitempty" json:"sender,omitempty"`
}

// PutContractsContractIdAbiJSONBody defines parameters for PutContractsContractIdAbi.
type PutContractsContractIdAbiJSONBody = ABI

// GetContractsContractIdMethodsMethodIdParams defines parameters for GetContractsContractIdMethodsMethodId.
type GetContractsContractIdMethodsMethodIdParams struct {
	Params *[]string `form:"params,omitempty" json:"params,omitempty"`
	Sender *string   `form:"sender,omitempty" json:"sender,omitempty"`
}

// GetLogsParams defines parameters for GetLogs.
type GetLogsParams struct {
	// Address of the smart contract to get events from
	Address string `form:"address" json:"address"`

	// Pinning transaction number for filtering logs from pinTx
	PinFrom *int `form:"pinFrom,omitempty" json:"pinFrom,omitempty"`

	// Pinning transaction number for filtering logs to pinTx
	PinTo  *int     `form:"pinTo,omitempty" json:"pinTo,omitempty"`
	Topics []string `form:"topics" json:"topics"`

	// Number of the page to be returned, default is 0 (first page)
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Size of the page returned. Typically mustn't be changed on paging through because it will be required to recalculate position of the first element = page * size
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetPeersParams defines parameters for GetPeers.
type GetPeersParams struct {
	Status *interface{} `form:"status,omitempty" json:"status,omitempty"`

	// Number of the page to be returned, default is 0 (first page)
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Size of the page returned. Typically mustn't be changed on paging through because it will be required to recalculate position of the first element = page * size
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetFilteredTransactionsParams defines parameters for GetFilteredTransactions.
type GetFilteredTransactionsParams struct {
	// List of accounts that must be used for filtering transactions, when empty - then all transactions will be returned
	Accounts *[]string `form:"accounts,omitempty" json:"accounts,omitempty"`

	// Number of the block to see for transactions (optional)
	Block     *int                                    `form:"block,omitempty" json:"block,omitempty"`
	Direction *GetFilteredTransactionsParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`

	// Sort fetched transactions in ascending or descending order by 'sortCriteria'
	SortOrder *GetFilteredTransactionsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// Criteria to sort transactions by, NONCE is suited for one account transactions ordering, TIMESTAMP for many accounts ordering
	SortCriteria *GetFilteredTransactionsParamsSortCriteria `form:"sortCriteria,omitempty" json:"sortCriteria,omitempty"`

	// Filter transactions by type, leave empty or -1 to not apply this filter
	TxType *GetFilteredTransactionsParamsTxType `form:"txType,omitempty" json:"txType,omitempty"`

	// Select transactions with statuses - Confirmed, Unconfirmed or Both
	ConfirmationStatus *GetFilteredTransactionsParamsConfirmationStatus `form:"confirmationStatus,omitempty" json:"confirmationStatus,omitempty"`

	// Number of the page to be returned, default is 0 (first page)
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Size of the page returned. Typically mustn't be changed on paging through because it will be required to recalculate position of the first element = page * size
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetFilteredTransactionsParamsDirection defines parameters for GetFilteredTransactions.
type GetFilteredTransactionsParamsDirection string

// GetFilteredTransactionsParamsSortOrder defines parameters for GetFilteredTransactions.
type GetFilteredTransactionsParamsSortOrder string

// GetFilteredTransactionsParamsSortCriteria defines parameters for GetFilteredTransactions.
type GetFilteredTransactionsParamsSortCriteria string

// GetFilteredTransactionsParamsTxType defines parameters for GetFilteredTransactions.
type GetFilteredTransactionsParamsTxType int

// GetFilteredTransactionsParamsConfirmationStatus defines parameters for GetFilteredTransactions.
type GetFilteredTransactionsParamsConfirmationStatus string

// SendRawTransactionJSONBody defines parameters for SendRawTransaction.
type SendRawTransactionJSONBody = RawTransaction

// EstimateTxFuelJSONBody defines parameters for EstimateTxFuel.
type EstimateTxFuelJSONBody interface{}

// PutContractsContractIdAbiJSONRequestBody defines body for PutContractsContractIdAbi for application/json ContentType.
type PutContractsContractIdAbiJSONRequestBody = PutContractsContractIdAbiJSONBody

// SendRawTransactionJSONRequestBody defines body for SendRawTransaction for application/json ContentType.
type SendRawTransactionJSONRequestBody = SendRawTransactionJSONBody

// EstimateTxFuelJSONRequestBody defines body for EstimateTxFuel for application/json ContentType.
type EstimateTxFuelJSONRequestBody EstimateTxFuelJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all user accounts
	// (GET /accounts)
	GetAccounts(w http.ResponseWriter, r *http.Request, params GetAccountsParams)
	// Get user's account by id
	// (GET /accounts/{accountId})
	GetAccountsAccountId(w http.ResponseWriter, r *http.Request, accountId string)
	// Call read method of the contract
	// (GET /contracts/{contractId})
	GetContractsContractId(w http.ResponseWriter, r *http.Request, contractId string, params GetContractsContractIdParams)
	// Get ABI for the contract
	// (GET /contracts/{contractId}/abi)
	GetContractsContractIdAbi(w http.ResponseWriter, r *http.Request, contractId string)
	// Save ABI for the contract
	// (PUT /contracts/{contractId}/abi)
	PutContractsContractIdAbi(w http.ResponseWriter, r *http.Request, contractId string)
	// Get code hash and contract code
	// (GET /contracts/{contractId}/code)
	GetContractsContractIdCode(w http.ResponseWriter, r *http.Request, contractId string)
	// Call read method of the contract
	// (GET /contracts/{contractId}/methods/{methodId})
	GetContractsContractIdMethodsMethodId(w http.ResponseWriter, r *http.Request, contractId string, methodId string, params GetContractsContractIdMethodsMethodIdParams)
	// Get SMC logs by filter
	// (GET /logs)
	GetLogs(w http.ResponseWriter, r *http.Request, params GetLogsParams)
	// Get general information about LunaOne network
	// (GET /network-info)
	GetNetworkInfo(w http.ResponseWriter, r *http.Request)
	// Get all peers for this node
	// (GET /peers)
	GetPeers(w http.ResponseWriter, r *http.Request, params GetPeersParams)
	// Get information about pin transaction
	// (GET /pin-number)
	GetPinNumber(w http.ResponseWriter, r *http.Request)
	// Get node's pubsub readiness status
	// (GET /pubsub)
	GetPubsub(w http.ResponseWriter, r *http.Request)
	// Get node's diagnosis stats
	// (GET /system)
	GetSystem(w http.ResponseWriter, r *http.Request)
	// Get confirmed and unconfirmed transactions with filter
	// (GET /transactions)
	GetFilteredTransactions(w http.ResponseWriter, r *http.Request, params GetFilteredTransactionsParams)
	// Send signed transaction
	// (POST /transactions)
	SendRawTransaction(w http.ResponseWriter, r *http.Request)
	// Estimate fuel limit for tx
	// (POST /transactions/estimate)
	EstimateTxFuel(w http.ResponseWriter, r *http.Request)
	// Get confirmed transaction by its hash
	// (GET /transactions/{txHash})
	GetTransactionByHash(w http.ResponseWriter, r *http.Request, txHash string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetAccounts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountsParams

	// ------------- Optional query parameter "sortOrder" -------------
	if paramValue := r.URL.Query().Get("sortOrder"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", r.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortOrder", Err: err})
		return
	}

	// ------------- Optional query parameter "sortCriteria" -------------
	if paramValue := r.URL.Query().Get("sortCriteria"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sortCriteria", r.URL.Query(), &params.SortCriteria)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortCriteria", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------
	if paramValue := r.URL.Query().Get("page"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------
	if paramValue := r.URL.Query().Get("pageSize"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccounts(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) GetAccountsAccountId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameter("simple", false, "accountId", chi.URLParam(r, "accountId"), &accountId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountsAccountId(w, r, accountId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetContractsContractId operation middleware
func (siw *ServerInterfaceWrapper) GetContractsContractId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "contractId" -------------
	var contractId string

	err = runtime.BindStyledParameter("simple", false, "contractId", chi.URLParam(r, "contractId"), &contractId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contractId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContractsContractIdParams

	// ------------- Optional query parameter "params" -------------
	if paramValue := r.URL.Query().Get("params"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "params", r.URL.Query(), &params.Params)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "params", Err: err})
		return
	}

	// ------------- Optional query parameter "sender" -------------
	if paramValue := r.URL.Query().Get("sender"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sender", r.URL.Query(), &params.Sender)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sender", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContractsContractId(w, r, contractId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetContractsContractIdAbi operation middleware
func (siw *ServerInterfaceWrapper) GetContractsContractIdAbi(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "contractId" -------------
	var contractId string

	err = runtime.BindStyledParameter("simple", false, "contractId", chi.URLParam(r, "contractId"), &contractId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contractId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContractsContractIdAbi(w, r, contractId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PutContractsContractIdAbi operation middleware
func (siw *ServerInterfaceWrapper) PutContractsContractIdAbi(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "contractId" -------------
	var contractId string

	err = runtime.BindStyledParameter("simple", false, "contractId", chi.URLParam(r, "contractId"), &contractId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contractId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutContractsContractIdAbi(w, r, contractId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetContractsContractIdCode operation middleware
func (siw *ServerInterfaceWrapper) GetContractsContractIdCode(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "contractId" -------------
	var contractId string

	err = runtime.BindStyledParameter("simple", false, "contractId", chi.URLParam(r, "contractId"), &contractId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contractId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContractsContractIdCode(w, r, contractId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetContractsContractIdMethodsMethodId operation middleware
func (siw *ServerInterfaceWrapper) GetContractsContractIdMethodsMethodId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "contractId" -------------
	var contractId string

	err = runtime.BindStyledParameter("simple", false, "contractId", chi.URLParam(r, "contractId"), &contractId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contractId", Err: err})
		return
	}

	// ------------- Path parameter "methodId" -------------
	var methodId string

	err = runtime.BindStyledParameter("simple", false, "methodId", chi.URLParam(r, "methodId"), &methodId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "methodId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContractsContractIdMethodsMethodIdParams

	// ------------- Optional query parameter "params" -------------
	if paramValue := r.URL.Query().Get("params"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", false, false, "params", r.URL.Query(), &params.Params)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "params", Err: err})
		return
	}

	// ------------- Optional query parameter "sender" -------------
	if paramValue := r.URL.Query().Get("sender"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sender", r.URL.Query(), &params.Sender)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sender", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContractsContractIdMethodsMethodId(w, r, contractId, methodId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetLogs operation middleware
func (siw *ServerInterfaceWrapper) GetLogs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLogsParams

	// ------------- Required query parameter "address" -------------
	if paramValue := r.URL.Query().Get("address"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "address"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "address", r.URL.Query(), &params.Address)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// ------------- Optional query parameter "pinFrom" -------------
	if paramValue := r.URL.Query().Get("pinFrom"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "pinFrom", r.URL.Query(), &params.PinFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pinFrom", Err: err})
		return
	}

	// ------------- Optional query parameter "pinTo" -------------
	if paramValue := r.URL.Query().Get("pinTo"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "pinTo", r.URL.Query(), &params.PinTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pinTo", Err: err})
		return
	}

	// ------------- Required query parameter "topics" -------------
	if paramValue := r.URL.Query().Get("topics"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "topics"})
		return
	}

	err = runtime.BindQueryParameter("form", false, true, "topics", r.URL.Query(), &params.Topics)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topics", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------
	if paramValue := r.URL.Query().Get("page"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------
	if paramValue := r.URL.Query().Get("pageSize"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogs(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetNetworkInfo operation middleware
func (siw *ServerInterfaceWrapper) GetNetworkInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNetworkInfo(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPeers operation middleware
func (siw *ServerInterfaceWrapper) GetPeers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPeersParams

	// ------------- Optional query parameter "status" -------------
	if paramValue := r.URL.Query().Get("status"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------
	if paramValue := r.URL.Query().Get("page"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------
	if paramValue := r.URL.Query().Get("pageSize"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPeers(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPinNumber operation middleware
func (siw *ServerInterfaceWrapper) GetPinNumber(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPinNumber(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPubsub operation middleware
func (siw *ServerInterfaceWrapper) GetPubsub(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPubsub(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystem(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetFilteredTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetFilteredTransactions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFilteredTransactionsParams

	// ------------- Optional query parameter "accounts" -------------
	if paramValue := r.URL.Query().Get("accounts"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", false, false, "accounts", r.URL.Query(), &params.Accounts)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accounts", Err: err})
		return
	}

	// ------------- Optional query parameter "block" -------------
	if paramValue := r.URL.Query().Get("block"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "block", r.URL.Query(), &params.Block)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "block", Err: err})
		return
	}

	// ------------- Optional query parameter "direction" -------------
	if paramValue := r.URL.Query().Get("direction"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "direction", r.URL.Query(), &params.Direction)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "direction", Err: err})
		return
	}

	// ------------- Optional query parameter "sortOrder" -------------
	if paramValue := r.URL.Query().Get("sortOrder"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", r.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortOrder", Err: err})
		return
	}

	// ------------- Optional query parameter "sortCriteria" -------------
	if paramValue := r.URL.Query().Get("sortCriteria"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sortCriteria", r.URL.Query(), &params.SortCriteria)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortCriteria", Err: err})
		return
	}

	// ------------- Optional query parameter "txType" -------------
	if paramValue := r.URL.Query().Get("txType"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "txType", r.URL.Query(), &params.TxType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "txType", Err: err})
		return
	}

	// ------------- Optional query parameter "confirmationStatus" -------------
	if paramValue := r.URL.Query().Get("confirmationStatus"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "confirmationStatus", r.URL.Query(), &params.ConfirmationStatus)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "confirmationStatus", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------
	if paramValue := r.URL.Query().Get("page"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------
	if paramValue := r.URL.Query().Get("pageSize"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFilteredTransactions(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// SendRawTransaction operation middleware
func (siw *ServerInterfaceWrapper) SendRawTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendRawTransaction(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// EstimateTxFuel operation middleware
func (siw *ServerInterfaceWrapper) EstimateTxFuel(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EstimateTxFuel(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetTransactionByHash operation middleware
func (siw *ServerInterfaceWrapper) GetTransactionByHash(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "txHash" -------------
	var txHash string

	err = runtime.BindStyledParameter("simple", false, "txHash", chi.URLParam(r, "txHash"), &txHash)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "txHash", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BasicScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransactionByHash(w, r, txHash)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts", wrapper.GetAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/{accountId}", wrapper.GetAccountsAccountId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/contracts/{contractId}", wrapper.GetContractsContractId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/contracts/{contractId}/abi", wrapper.GetContractsContractIdAbi)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/contracts/{contractId}/abi", wrapper.PutContractsContractIdAbi)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/contracts/{contractId}/code", wrapper.GetContractsContractIdCode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/contracts/{contractId}/methods/{methodId}", wrapper.GetContractsContractIdMethodsMethodId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs", wrapper.GetLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/network-info", wrapper.GetNetworkInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/peers", wrapper.GetPeers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pin-number", wrapper.GetPinNumber)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pubsub", wrapper.GetPubsub)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system", wrapper.GetSystem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/transactions", wrapper.GetFilteredTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/transactions", wrapper.SendRawTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/transactions/estimate", wrapper.EstimateTxFuel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/transactions/{txHash}", wrapper.GetTransactionByHash)
	})

	return r
}
