// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: consensus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfirmedSet - what one validator believes is confirmed and ready to be
// settled, sent at the start of an epoch. The set a commit transaction may
// settle is the sites a quorum of validators independently reported, so that a
// proposer cannot settle a site nobody else has confirmed.
type ConfirmedSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch   int64    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`    // the commit-transaction number being agreed
	SiteIds [][]byte `protobuf:"bytes,2,rep,name=siteIds,proto3" json:"siteIds,omitempty"` // uuid bytes
}

func (x *ConfirmedSet) Reset() {
	*x = ConfirmedSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmedSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedSet) ProtoMessage() {}

func (x *ConfirmedSet) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedSet.ProtoReflect.Descriptor instead.
func (*ConfirmedSet) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmedSet) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ConfirmedSet) GetSiteIds() [][]byte {
	if x != nil {
		return x.SiteIds
	}
	return nil
}

// PinProposal - the proposer's candidate commit transaction for an epoch, with
// the evidence that justifies it.
//
// A validator checks a proposal by counting, in the reports it holds, how many
// validators reported each site the proposal settles. Doing that against only
// the reports that happened to arrive makes the check depend on delivery order:
// a report still in flight is a report not counted, so a receiver under-counts
// and refuses a proposal that is perfectly justified. With no slack in the
// quorum - three live validators and a quorum of three - that is not a rare
// race, it is the normal case, and the chain stops.
//
// So the proposer carries the signed reports it counted. They are the same
// messages the receiver would have received anyway, each still signed by the
// validator that wrote it, so folding them in adds no trust: the receiver
// verifies every one before counting it, and reaches the same conclusion the
// proposer did from the same evidence.
type PinProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch   int64                `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Round   uint32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"` // view-change round; the proposer rotates with it
	Pin     *TxPin               `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	Reports []*ConsensusEnvelope `protobuf:"bytes,4,rep,name=reports,proto3" json:"reports,omitempty"` // signed ConfirmedSet messages
}

func (x *PinProposal) Reset() {
	*x = PinProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinProposal) ProtoMessage() {}

func (x *PinProposal) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinProposal.ProtoReflect.Descriptor instead.
func (*PinProposal) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *PinProposal) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PinProposal) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PinProposal) GetPin() *TxPin {
	if x != nil {
		return x.Pin
	}
	return nil
}

func (x *PinProposal) GetReports() []*ConsensusEnvelope {
	if x != nil {
		return x.Reports
	}
	return nil
}

// PinVote - one validator's agreement with a proposal, as a signature over the
// proposal's prototype hash. Collected into the QuorumCert the proposer
// attaches before publishing.
type PinVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch   int64  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Round   uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	PinHash []byte `protobuf:"bytes,3,opt,name=pinHash,proto3" json:"pinHash,omitempty"` // the prototype hash being agreed to
	Sign    []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`       // signature over pinHash
}

func (x *PinVote) Reset() {
	*x = PinVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinVote) ProtoMessage() {}

func (x *PinVote) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinVote.ProtoReflect.Descriptor instead.
func (*PinVote) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *PinVote) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PinVote) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PinVote) GetPinHash() []byte {
	if x != nil {
		return x.PinHash
	}
	return nil
}

func (x *PinVote) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

// ViewChange - this validator has given up on the round's proposer.
type ViewChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch int64  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Round uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"` // the round being abandoned
}

func (x *ViewChange) Reset() {
	*x = ViewChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChange) ProtoMessage() {}

func (x *ViewChange) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChange.ProtoReflect.Descriptor instead.
func (*ViewChange) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *ViewChange) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ViewChange) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

// ConsensusEnvelope - any consensus message, signed by the validator that sent
// it. Signed over the envelope with pk and sign cleared, so the signature covers
// the payload and nothing else.
type ConsensusEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pk   []byte `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Sign []byte `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*ConsensusEnvelope_Confirmed
	//	*ConsensusEnvelope_Proposal
	//	*ConsensusEnvelope_Vote
	//	*ConsensusEnvelope_ViewChange
	Payload isConsensusEnvelope_Payload `protobuf_oneof:"payload"`
}

func (x *ConsensusEnvelope) Reset() {
	*x = ConsensusEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusEnvelope) ProtoMessage() {}

func (x *ConsensusEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusEnvelope.ProtoReflect.Descriptor instead.
func (*ConsensusEnvelope) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *ConsensusEnvelope) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *ConsensusEnvelope) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (m *ConsensusEnvelope) GetPayload() isConsensusEnvelope_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ConsensusEnvelope) GetConfirmed() *ConfirmedSet {
	if x, ok := x.GetPayload().(*ConsensusEnvelope_Confirmed); ok {
		return x.Confirmed
	}
	return nil
}

func (x *ConsensusEnvelope) GetProposal() *PinProposal {
	if x, ok := x.GetPayload().(*ConsensusEnvelope_Proposal); ok {
		return x.Proposal
	}
	return nil
}

func (x *ConsensusEnvelope) GetVote() *PinVote {
	if x, ok := x.GetPayload().(*ConsensusEnvelope_Vote); ok {
		return x.Vote
	}
	return nil
}

func (x *ConsensusEnvelope) GetViewChange() *ViewChange {
	if x, ok := x.GetPayload().(*ConsensusEnvelope_ViewChange); ok {
		return x.ViewChange
	}
	return nil
}

type isConsensusEnvelope_Payload interface {
	isConsensusEnvelope_Payload()
}

type ConsensusEnvelope_Confirmed struct {
	Confirmed *ConfirmedSet `protobuf:"bytes,3,opt,name=confirmed,proto3,oneof"`
}

type ConsensusEnvelope_Proposal struct {
	Proposal *PinProposal `protobuf:"bytes,4,opt,name=proposal,proto3,oneof"`
}

type ConsensusEnvelope_Vote struct {
	Vote *PinVote `protobuf:"bytes,5,opt,name=vote,proto3,oneof"`
}

type ConsensusEnvelope_ViewChange struct {
	ViewChange *ViewChange `protobuf:"bytes,6,opt,name=viewChange,proto3,oneof"`
}

func (*ConsensusEnvelope_Confirmed) isConsensusEnvelope_Payload() {}

func (*ConsensusEnvelope_Proposal) isConsensusEnvelope_Payload() {}

func (*ConsensusEnvelope_Vote) isConsensusEnvelope_Payload() {}

func (*ConsensusEnvelope_ViewChange) isConsensusEnvelope_Payload() {}

var File_consensus_proto protoreflect.FileDescriptor

var file_consensus_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x74, 0x78, 0x70, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x53,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65,
	0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x49,
	0x64, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1b,
	0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x78, 0x50, 0x69, 0x6e, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x12, 0x2f, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x63, 0x0a, 0x07,
	0x50, 0x69, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x69, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x22, 0x38, 0x0a, 0x0a, 0x56, 0x69, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xf8, 0x01, 0x0a, 0x11,
	0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70,
	0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x53, 0x65, 0x74, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x69, 0x6e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x21, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x69, 0x6e, 0x56, 0x6f, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x76, 0x69, 0x65,
	0x77, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0a, 0x76, 0x69, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consensus_proto_rawDescOnce sync.Once
	file_consensus_proto_rawDescData = file_consensus_proto_rawDesc
)

func file_consensus_proto_rawDescGZIP() []byte {
	file_consensus_proto_rawDescOnce.Do(func() {
		file_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(file_consensus_proto_rawDescData)
	})
	return file_consensus_proto_rawDescData
}

var file_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_consensus_proto_goTypes = []interface{}{
	(*ConfirmedSet)(nil),      // 0: pb.ConfirmedSet
	(*PinProposal)(nil),       // 1: pb.PinProposal
	(*PinVote)(nil),           // 2: pb.PinVote
	(*ViewChange)(nil),        // 3: pb.ViewChange
	(*ConsensusEnvelope)(nil), // 4: pb.ConsensusEnvelope
	(*TxPin)(nil),             // 5: pb.TxPin
}
var file_consensus_proto_depIdxs = []int32{
	5, // 0: pb.PinProposal.pin:type_name -> pb.TxPin
	4, // 1: pb.PinProposal.reports:type_name -> pb.ConsensusEnvelope
	0, // 2: pb.ConsensusEnvelope.confirmed:type_name -> pb.ConfirmedSet
	1, // 3: pb.ConsensusEnvelope.proposal:type_name -> pb.PinProposal
	2, // 4: pb.ConsensusEnvelope.vote:type_name -> pb.PinVote
	3, // 5: pb.ConsensusEnvelope.viewChange:type_name -> pb.ViewChange
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_consensus_proto_init() }
func file_consensus_proto_init() {
	if File_consensus_proto != nil {
		return
	}
	file_txpin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_consensus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmedSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsensusEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_consensus_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*ConsensusEnvelope_Confirmed)(nil),
		(*ConsensusEnvelope_Proposal)(nil),
		(*ConsensusEnvelope_Vote)(nil),
		(*ConsensusEnvelope_ViewChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consensus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_proto_goTypes,
		DependencyIndexes: file_consensus_proto_depIdxs,
		MessageInfos:      file_consensus_proto_msgTypes,
	}.Build()
	File_consensus_proto = out.File
	file_consensus_proto_rawDesc = nil
	file_consensus_proto_goTypes = nil
	file_consensus_proto_depIdxs = nil
}
