// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grapetx.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrapeTxRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId    []byte                       `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Seq       uint64                       `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Tx        []byte                       `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	Addresses []*GrapeTxRecord_AddressInfo `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Version   VersionType                  `protobuf:"varint,5,opt,name=version,proto3,enum=pb.VersionType" json:"version,omitempty"`
	Ids       *Ids                         `protobuf:"bytes,6,opt,name=ids,proto3" json:"ids,omitempty"`
	// Types that are assignable to Transaction:
	//
	//	*GrapeTxRecord_Txv1
	//	*GrapeTxRecord_Txv2
	Transaction isGrapeTxRecord_Transaction `protobuf_oneof:"transaction"`
	Txidmajor   uint64                      `protobuf:"varint,12,opt,name=txidmajor,proto3" json:"txidmajor,omitempty"`
	Txidminor   uint32                      `protobuf:"varint,13,opt,name=txidminor,proto3" json:"txidminor,omitempty"`
	Txidid      []byte                      `protobuf:"bytes,14,opt,name=txidid,proto3" json:"txidid,omitempty"`
	// Processor attribution for the site this record's transaction was
	// encapsulated into, mirroring Node fields 9-11. It has to travel on the
	// record as well as on the site: a subscribing peer does not rebuild the
	// sender's site from a pb.Node, it builds its own from the transaction (see
	// diffusion/subscribe.go), so the record is the only place the attribution
	// could reach it.
	//
	// 15-17 are the next free numbers: 1-6 and 12-14 are in use, 7-9 are
	// reserved, and 10-11 belong to the `transaction` oneof.
	ProcessorAddress []byte `protobuf:"bytes,15,opt,name=processor_address,json=processorAddress,proto3" json:"processor_address,omitempty"`
	ProcessorPk      []byte `protobuf:"bytes,16,opt,name=processor_pk,json=processorPk,proto3" json:"processor_pk,omitempty"`
	ProcessorSig     []byte `protobuf:"bytes,17,opt,name=processor_sig,json=processorSig,proto3" json:"processor_sig,omitempty"`
}

func (x *GrapeTxRecord) Reset() {
	*x = GrapeTxRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grapetx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrapeTxRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrapeTxRecord) ProtoMessage() {}

func (x *GrapeTxRecord) ProtoReflect() protoreflect.Message {
	mi := &file_grapetx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrapeTxRecord.ProtoReflect.Descriptor instead.
func (*GrapeTxRecord) Descriptor() ([]byte, []int) {
	return file_grapetx_proto_rawDescGZIP(), []int{0}
}

func (x *GrapeTxRecord) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *GrapeTxRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GrapeTxRecord) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *GrapeTxRecord) GetAddresses() []*GrapeTxRecord_AddressInfo {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GrapeTxRecord) GetVersion() VersionType {
	if x != nil {
		return x.Version
	}
	return VersionType_TXV0
}

func (x *GrapeTxRecord) GetIds() *Ids {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (m *GrapeTxRecord) GetTransaction() isGrapeTxRecord_Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (x *GrapeTxRecord) GetTxv1() *Txv1 {
	if x, ok := x.GetTransaction().(*GrapeTxRecord_Txv1); ok {
		return x.Txv1
	}
	return nil
}

func (x *GrapeTxRecord) GetTxv2() *Txv2 {
	if x, ok := x.GetTransaction().(*GrapeTxRecord_Txv2); ok {
		return x.Txv2
	}
	return nil
}

func (x *GrapeTxRecord) GetTxidmajor() uint64 {
	if x != nil {
		return x.Txidmajor
	}
	return 0
}

func (x *GrapeTxRecord) GetTxidminor() uint32 {
	if x != nil {
		return x.Txidminor
	}
	return 0
}

func (x *GrapeTxRecord) GetTxidid() []byte {
	if x != nil {
		return x.Txidid
	}
	return nil
}

func (x *GrapeTxRecord) GetProcessorAddress() []byte {
	if x != nil {
		return x.ProcessorAddress
	}
	return nil
}

func (x *GrapeTxRecord) GetProcessorPk() []byte {
	if x != nil {
		return x.ProcessorPk
	}
	return nil
}

func (x *GrapeTxRecord) GetProcessorSig() []byte {
	if x != nil {
		return x.ProcessorSig
	}
	return nil
}

type isGrapeTxRecord_Transaction interface {
	isGrapeTxRecord_Transaction()
}

type GrapeTxRecord_Txv1 struct {
	Txv1 *Txv1 `protobuf:"bytes,10,opt,name=txv1,proto3,oneof"`
}

type GrapeTxRecord_Txv2 struct {
	Txv2 *Txv2 `protobuf:"bytes,11,opt,name=txv2,proto3,oneof"`
}

func (*GrapeTxRecord_Txv1) isGrapeTxRecord_Transaction() {}

func (*GrapeTxRecord_Txv2) isGrapeTxRecord_Transaction() {}

type GrapeTxRecord_AddressInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiaddr []byte `protobuf:"bytes,1,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
}

func (x *GrapeTxRecord_AddressInfo) Reset() {
	*x = GrapeTxRecord_AddressInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grapetx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrapeTxRecord_AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrapeTxRecord_AddressInfo) ProtoMessage() {}

func (x *GrapeTxRecord_AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grapetx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrapeTxRecord_AddressInfo.ProtoReflect.Descriptor instead.
func (*GrapeTxRecord_AddressInfo) Descriptor() ([]byte, []int) {
	return file_grapetx_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GrapeTxRecord_AddressInfo) GetMultiaddr() []byte {
	if x != nil {
		return x.Multiaddr
	}
	return nil
}

var File_grapetx_proto protoreflect.FileDescriptor

var file_grapetx_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x72, 0x61, 0x70, 0x65, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x09, 0x69, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x74, 0x78, 0x76, 0x58, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x04, 0x0a, 0x0d, 0x47,
	0x72, 0x61, 0x70, 0x65, 0x54, 0x78, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70,
	0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x3b, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x72, 0x61, 0x70, 0x65, 0x54, 0x78, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x64, 0x73, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x78,
	0x76, 0x31, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78,
	0x76, 0x31, 0x48, 0x00, 0x52, 0x04, 0x74, 0x78, 0x76, 0x31, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x78,
	0x76, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78,
	0x76, 0x32, 0x48, 0x00, 0x52, 0x04, 0x74, 0x78, 0x76, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x78,
	0x69, 0x64, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74,
	0x78, 0x69, 0x64, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x78, 0x69, 0x64,
	0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x78, 0x69,
	0x64, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x69, 0x64, 0x69, 0x64,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x69, 0x64, 0x69, 0x64, 0x12, 0x2b,
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x70, 0x6b, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x50, 0x6b, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x73, 0x69, 0x67, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x53, 0x69, 0x67, 0x1a, 0x2b, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x61, 0x64, 0x64, 0x72,
	0x42, 0x0d, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4a,
	0x04, 0x08, 0x07, 0x10, 0x0a, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grapetx_proto_rawDescOnce sync.Once
	file_grapetx_proto_rawDescData = file_grapetx_proto_rawDesc
)

func file_grapetx_proto_rawDescGZIP() []byte {
	file_grapetx_proto_rawDescOnce.Do(func() {
		file_grapetx_proto_rawDescData = protoimpl.X.CompressGZIP(file_grapetx_proto_rawDescData)
	})
	return file_grapetx_proto_rawDescData
}

var file_grapetx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grapetx_proto_goTypes = []interface{}{
	(*GrapeTxRecord)(nil),             // 0: pb.GrapeTxRecord
	(*GrapeTxRecord_AddressInfo)(nil), // 1: pb.GrapeTxRecord.AddressInfo
	(VersionType)(0),                  // 2: pb.VersionType
	(*Ids)(nil),                       // 3: pb.Ids
	(*Txv1)(nil),                      // 4: pb.Txv1
	(*Txv2)(nil),                      // 5: pb.Txv2
}
var file_grapetx_proto_depIdxs = []int32{
	1, // 0: pb.GrapeTxRecord.addresses:type_name -> pb.GrapeTxRecord.AddressInfo
	2, // 1: pb.GrapeTxRecord.version:type_name -> pb.VersionType
	3, // 2: pb.GrapeTxRecord.ids:type_name -> pb.Ids
	4, // 3: pb.GrapeTxRecord.txv1:type_name -> pb.Txv1
	5, // 4: pb.GrapeTxRecord.txv2:type_name -> pb.Txv2
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grapetx_proto_init() }
func file_grapetx_proto_init() {
	if File_grapetx_proto != nil {
		return
	}
	file_ids_proto_init()
	file_txvX_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grapetx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrapeTxRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grapetx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrapeTxRecord_AddressInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grapetx_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GrapeTxRecord_Txv1)(nil),
		(*GrapeTxRecord_Txv2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grapetx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grapetx_proto_goTypes,
		DependencyIndexes: file_grapetx_proto_depIdxs,
		MessageInfos:      file_grapetx_proto_msgTypes,
	}.Build()
	File_grapetx_proto = out.File
	file_grapetx_proto_rawDesc = nil
	file_grapetx_proto_goTypes = nil
	file_grapetx_proto_depIdxs = nil
}
