// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: txgen.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoboTraderClient is the client API for RoboTrader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoboTraderClient interface {
	GenerateTx(ctx context.Context, in *TxGenerateRequest, opts ...grpc.CallOption) (*TxGenerateResponse, error)
	PublishTx(ctx context.Context, in *TxPublishRequest, opts ...grpc.CallOption) (*TxPublishResponse, error)
	GetBalances(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetWallets(ctx context.Context, in *WalletsRequest, opts ...grpc.CallOption) (*WalletsResponse, error)
	GetTxCount(ctx context.Context, in *TxCountRequest, opts ...grpc.CallOption) (*TxCountResponse, error)
	WatchDog(ctx context.Context, in *WatchDogRequest, opts ...grpc.CallOption) (*WatchDogResponse, error)
}

type roboTraderClient struct {
	cc grpc.ClientConnInterface
}

func NewRoboTraderClient(cc grpc.ClientConnInterface) RoboTraderClient {
	return &roboTraderClient{cc}
}

func (c *roboTraderClient) GenerateTx(ctx context.Context, in *TxGenerateRequest, opts ...grpc.CallOption) (*TxGenerateResponse, error) {
	out := new(TxGenerateResponse)
	err := c.cc.Invoke(ctx, "/pb.RoboTrader/GenerateTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roboTraderClient) PublishTx(ctx context.Context, in *TxPublishRequest, opts ...grpc.CallOption) (*TxPublishResponse, error) {
	out := new(TxPublishResponse)
	err := c.cc.Invoke(ctx, "/pb.RoboTrader/PublishTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roboTraderClient) GetBalances(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/pb.RoboTrader/GetBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roboTraderClient) GetWallets(ctx context.Context, in *WalletsRequest, opts ...grpc.CallOption) (*WalletsResponse, error) {
	out := new(WalletsResponse)
	err := c.cc.Invoke(ctx, "/pb.RoboTrader/GetWallets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roboTraderClient) GetTxCount(ctx context.Context, in *TxCountRequest, opts ...grpc.CallOption) (*TxCountResponse, error) {
	out := new(TxCountResponse)
	err := c.cc.Invoke(ctx, "/pb.RoboTrader/GetTxCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roboTraderClient) WatchDog(ctx context.Context, in *WatchDogRequest, opts ...grpc.CallOption) (*WatchDogResponse, error) {
	out := new(WatchDogResponse)
	err := c.cc.Invoke(ctx, "/pb.RoboTrader/WatchDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoboTraderServer is the server API for RoboTrader service.
// All implementations must embed UnimplementedRoboTraderServer
// for forward compatibility
type RoboTraderServer interface {
	GenerateTx(context.Context, *TxGenerateRequest) (*TxGenerateResponse, error)
	PublishTx(context.Context, *TxPublishRequest) (*TxPublishResponse, error)
	GetBalances(context.Context, *BalanceRequest) (*BalanceResponse, error)
	GetWallets(context.Context, *WalletsRequest) (*WalletsResponse, error)
	GetTxCount(context.Context, *TxCountRequest) (*TxCountResponse, error)
	WatchDog(context.Context, *WatchDogRequest) (*WatchDogResponse, error)
	mustEmbedUnimplementedRoboTraderServer()
}

// UnimplementedRoboTraderServer must be embedded to have forward compatible implementations.
type UnimplementedRoboTraderServer struct {
}

func (UnimplementedRoboTraderServer) GenerateTx(context.Context, *TxGenerateRequest) (*TxGenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateTx not implemented")
}
func (UnimplementedRoboTraderServer) PublishTx(context.Context, *TxPublishRequest) (*TxPublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishTx not implemented")
}
func (UnimplementedRoboTraderServer) GetBalances(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalances not implemented")
}
func (UnimplementedRoboTraderServer) GetWallets(context.Context, *WalletsRequest) (*WalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallets not implemented")
}
func (UnimplementedRoboTraderServer) GetTxCount(context.Context, *TxCountRequest) (*TxCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxCount not implemented")
}
func (UnimplementedRoboTraderServer) WatchDog(context.Context, *WatchDogRequest) (*WatchDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchDog not implemented")
}
func (UnimplementedRoboTraderServer) mustEmbedUnimplementedRoboTraderServer() {}

// UnsafeRoboTraderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoboTraderServer will
// result in compilation errors.
type UnsafeRoboTraderServer interface {
	mustEmbedUnimplementedRoboTraderServer()
}

func RegisterRoboTraderServer(s grpc.ServiceRegistrar, srv RoboTraderServer) {
	s.RegisterService(&RoboTrader_ServiceDesc, srv)
}

func _RoboTrader_GenerateTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxGenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoboTraderServer).GenerateTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RoboTrader/GenerateTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoboTraderServer).GenerateTx(ctx, req.(*TxGenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoboTrader_PublishTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxPublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoboTraderServer).PublishTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RoboTrader/PublishTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoboTraderServer).PublishTx(ctx, req.(*TxPublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoboTrader_GetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoboTraderServer).GetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RoboTrader/GetBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoboTraderServer).GetBalances(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoboTrader_GetWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoboTraderServer).GetWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RoboTrader/GetWallets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoboTraderServer).GetWallets(ctx, req.(*WalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoboTrader_GetTxCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoboTraderServer).GetTxCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RoboTrader/GetTxCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoboTraderServer).GetTxCount(ctx, req.(*TxCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoboTrader_WatchDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchDogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoboTraderServer).WatchDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RoboTrader/WatchDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoboTraderServer).WatchDog(ctx, req.(*WatchDogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoboTrader_ServiceDesc is the grpc.ServiceDesc for RoboTrader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoboTrader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RoboTrader",
	HandlerType: (*RoboTraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateTx",
			Handler:    _RoboTrader_GenerateTx_Handler,
		},
		{
			MethodName: "PublishTx",
			Handler:    _RoboTrader_PublishTx_Handler,
		},
		{
			MethodName: "GetBalances",
			Handler:    _RoboTrader_GetBalances_Handler,
		},
		{
			MethodName: "GetWallets",
			Handler:    _RoboTrader_GetWallets_Handler,
		},
		{
			MethodName: "GetTxCount",
			Handler:    _RoboTrader_GetTxCount_Handler,
		},
		{
			MethodName: "WatchDog",
			Handler:    _RoboTrader_WatchDog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "txgen.proto",
}
