// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: txgen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchDogResponse_PEER_STATUS int32

const (
	WatchDogResponse_RUNNING WatchDogResponse_PEER_STATUS = 0
	WatchDogResponse_KILLED  WatchDogResponse_PEER_STATUS = 1
)

// Enum value maps for WatchDogResponse_PEER_STATUS.
var (
	WatchDogResponse_PEER_STATUS_name = map[int32]string{
		0: "RUNNING",
		1: "KILLED",
	}
	WatchDogResponse_PEER_STATUS_value = map[string]int32{
		"RUNNING": 0,
		"KILLED":  1,
	}
)

func (x WatchDogResponse_PEER_STATUS) Enum() *WatchDogResponse_PEER_STATUS {
	p := new(WatchDogResponse_PEER_STATUS)
	*p = x
	return p
}

func (x WatchDogResponse_PEER_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchDogResponse_PEER_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_txgen_proto_enumTypes[0].Descriptor()
}

func (WatchDogResponse_PEER_STATUS) Type() protoreflect.EnumType {
	return &file_txgen_proto_enumTypes[0]
}

func (x WatchDogResponse_PEER_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchDogResponse_PEER_STATUS.Descriptor instead.
func (WatchDogResponse_PEER_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{11, 0}
}

type TxGenerateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txrate     uint32 `protobuf:"varint,1,opt,name=txrate,proto3" json:"txrate,omitempty"`
	Duration   uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Txmax      uint32 `protobuf:"varint,3,opt,name=txmax,proto3" json:"txmax,omitempty"`
	Wallet     string `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Privatekey string `protobuf:"bytes,5,opt,name=privatekey,proto3" json:"privatekey,omitempty"`
	Publickey  string `protobuf:"bytes,6,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Network    uint32 `protobuf:"varint,7,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *TxGenerateRequest) Reset() {
	*x = TxGenerateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxGenerateRequest) ProtoMessage() {}

func (x *TxGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxGenerateRequest.ProtoReflect.Descriptor instead.
func (*TxGenerateRequest) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{0}
}

func (x *TxGenerateRequest) GetTxrate() uint32 {
	if x != nil {
		return x.Txrate
	}
	return 0
}

func (x *TxGenerateRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TxGenerateRequest) GetTxmax() uint32 {
	if x != nil {
		return x.Txmax
	}
	return 0
}

func (x *TxGenerateRequest) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *TxGenerateRequest) GetPrivatekey() string {
	if x != nil {
		return x.Privatekey
	}
	return ""
}

func (x *TxGenerateRequest) GetPublickey() string {
	if x != nil {
		return x.Publickey
	}
	return ""
}

func (x *TxGenerateRequest) GetNetwork() uint32 {
	if x != nil {
		return x.Network
	}
	return 0
}

type TxGenerateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration float32 `protobuf:"fixed32,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Txcount  int32   `protobuf:"varint,2,opt,name=txcount,proto3" json:"txcount,omitempty"`
}

func (x *TxGenerateResponse) Reset() {
	*x = TxGenerateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxGenerateResponse) ProtoMessage() {}

func (x *TxGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxGenerateResponse.ProtoReflect.Descriptor instead.
func (*TxGenerateResponse) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{1}
}

func (x *TxGenerateResponse) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TxGenerateResponse) GetTxcount() int32 {
	if x != nil {
		return x.Txcount
	}
	return 0
}

type TxPublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx *Txv1 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *TxPublishRequest) Reset() {
	*x = TxPublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPublishRequest) ProtoMessage() {}

func (x *TxPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPublishRequest.ProtoReflect.Descriptor instead.
func (*TxPublishRequest) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{2}
}

func (x *TxPublishRequest) GetTx() *Txv1 {
	if x != nil {
		return x.Tx
	}
	return nil
}

type TxPublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TxPublishResponse) Reset() {
	*x = TxPublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPublishResponse) ProtoMessage() {}

func (x *TxPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPublishResponse.ProtoReflect.Descriptor instead.
func (*TxPublishResponse) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{3}
}

func (x *TxPublishResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TxPublishResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WalletsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WalletsRequest) Reset() {
	*x = WalletsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletsRequest) ProtoMessage() {}

func (x *WalletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletsRequest.ProtoReflect.Descriptor instead.
func (*WalletsRequest) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{4}
}

type WalletsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wallets [][]byte `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
}

func (x *WalletsResponse) Reset() {
	*x = WalletsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletsResponse) ProtoMessage() {}

func (x *WalletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletsResponse.ProtoReflect.Descriptor instead.
func (*WalletsResponse) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{5}
}

func (x *WalletsResponse) GetWallets() [][]byte {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type BalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wallets [][]byte `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{6}
}

func (x *BalanceRequest) GetWallets() [][]byte {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type BalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balances [][]byte `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{7}
}

func (x *BalanceResponse) GetBalances() [][]byte {
	if x != nil {
		return x.Balances
	}
	return nil
}

type TxCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TxCountRequest) Reset() {
	*x = TxCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxCountRequest) ProtoMessage() {}

func (x *TxCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxCountRequest.ProtoReflect.Descriptor instead.
func (*TxCountRequest) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{8}
}

type TxCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Tps      float32 `protobuf:"fixed32,2,opt,name=tps,proto3" json:"tps,omitempty"`
	Avgdelay int64   `protobuf:"varint,3,opt,name=avgdelay,proto3" json:"avgdelay,omitempty"`
}

func (x *TxCountResponse) Reset() {
	*x = TxCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxCountResponse) ProtoMessage() {}

func (x *TxCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxCountResponse.ProtoReflect.Descriptor instead.
func (*TxCountResponse) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{9}
}

func (x *TxCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TxCountResponse) GetTps() float32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *TxCountResponse) GetAvgdelay() int64 {
	if x != nil {
		return x.Avgdelay
	}
	return 0
}

type WatchDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout int64 `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retries int32 `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
}

func (x *WatchDogRequest) Reset() {
	*x = WatchDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDogRequest) ProtoMessage() {}

func (x *WatchDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDogRequest.ProtoReflect.Descriptor instead.
func (*WatchDogRequest) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{10}
}

func (x *WatchDogRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *WatchDogRequest) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type WatchDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status WatchDogResponse_PEER_STATUS `protobuf:"varint,1,opt,name=status,proto3,enum=pb.WatchDogResponse_PEER_STATUS" json:"status,omitempty"`
}

func (x *WatchDogResponse) Reset() {
	*x = WatchDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txgen_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDogResponse) ProtoMessage() {}

func (x *WatchDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txgen_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDogResponse.ProtoReflect.Descriptor instead.
func (*WatchDogResponse) Descriptor() ([]byte, []int) {
	return file_txgen_proto_rawDescGZIP(), []int{11}
}

func (x *WatchDogResponse) GetStatus() WatchDogResponse_PEER_STATUS {
	if x != nil {
		return x.Status
	}
	return WatchDogResponse_RUNNING
}

var File_txgen_proto protoreflect.FileDescriptor

var file_txgen_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x78, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x0a, 0x74, 0x78, 0x76, 0x58, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01,
	0x0a, 0x11, 0x54, 0x78, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x78, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x6d, 0x61, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x78, 0x6d, 0x61, 0x78, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b,
	0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x4a, 0x0a,
	0x12, 0x54, 0x78, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x78, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x74, 0x78, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x10, 0x54, 0x78, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54,
	0x78, 0x76, 0x31, 0x52, 0x02, 0x74, 0x78, 0x22, 0x3d, 0x0a, 0x11, 0x54, 0x78, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x10, 0x0a, 0x0e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x0f, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x73, 0x22, 0x2a, 0x0a, 0x0e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x73, 0x22, 0x2d, 0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x22, 0x10, 0x0a, 0x0e, 0x54, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x55, 0x0a, 0x0f, 0x54, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74, 0x70, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x76, 0x67, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x61, 0x76, 0x67, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x45, 0x0a, 0x0f, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x22, 0x74, 0x0a, 0x10, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x45, 0x45, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x26,
	0x0a, 0x0b, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0b, 0x0a,
	0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x49,
	0x4c, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x32, 0xe0, 0x02, 0x0a, 0x0a, 0x52, 0x6f, 0x62, 0x6f, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x54, 0x78, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x78, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x78, 0x12,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x54, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x54,
	0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x6f, 0x67, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_txgen_proto_rawDescOnce sync.Once
	file_txgen_proto_rawDescData = file_txgen_proto_rawDesc
)

func file_txgen_proto_rawDescGZIP() []byte {
	file_txgen_proto_rawDescOnce.Do(func() {
		file_txgen_proto_rawDescData = protoimpl.X.CompressGZIP(file_txgen_proto_rawDescData)
	})
	return file_txgen_proto_rawDescData
}

var file_txgen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_txgen_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_txgen_proto_goTypes = []interface{}{
	(WatchDogResponse_PEER_STATUS)(0), // 0: pb.WatchDogResponse.PEER_STATUS
	(*TxGenerateRequest)(nil),         // 1: pb.TxGenerateRequest
	(*TxGenerateResponse)(nil),        // 2: pb.TxGenerateResponse
	(*TxPublishRequest)(nil),          // 3: pb.TxPublishRequest
	(*TxPublishResponse)(nil),         // 4: pb.TxPublishResponse
	(*WalletsRequest)(nil),            // 5: pb.WalletsRequest
	(*WalletsResponse)(nil),           // 6: pb.WalletsResponse
	(*BalanceRequest)(nil),            // 7: pb.BalanceRequest
	(*BalanceResponse)(nil),           // 8: pb.BalanceResponse
	(*TxCountRequest)(nil),            // 9: pb.TxCountRequest
	(*TxCountResponse)(nil),           // 10: pb.TxCountResponse
	(*WatchDogRequest)(nil),           // 11: pb.WatchDogRequest
	(*WatchDogResponse)(nil),          // 12: pb.WatchDogResponse
	(*Txv1)(nil),                      // 13: pb.Txv1
}
var file_txgen_proto_depIdxs = []int32{
	13, // 0: pb.TxPublishRequest.tx:type_name -> pb.Txv1
	0,  // 1: pb.WatchDogResponse.status:type_name -> pb.WatchDogResponse.PEER_STATUS
	1,  // 2: pb.RoboTrader.GenerateTx:input_type -> pb.TxGenerateRequest
	3,  // 3: pb.RoboTrader.PublishTx:input_type -> pb.TxPublishRequest
	7,  // 4: pb.RoboTrader.GetBalances:input_type -> pb.BalanceRequest
	5,  // 5: pb.RoboTrader.GetWallets:input_type -> pb.WalletsRequest
	9,  // 6: pb.RoboTrader.GetTxCount:input_type -> pb.TxCountRequest
	11, // 7: pb.RoboTrader.WatchDog:input_type -> pb.WatchDogRequest
	2,  // 8: pb.RoboTrader.GenerateTx:output_type -> pb.TxGenerateResponse
	4,  // 9: pb.RoboTrader.PublishTx:output_type -> pb.TxPublishResponse
	8,  // 10: pb.RoboTrader.GetBalances:output_type -> pb.BalanceResponse
	6,  // 11: pb.RoboTrader.GetWallets:output_type -> pb.WalletsResponse
	10, // 12: pb.RoboTrader.GetTxCount:output_type -> pb.TxCountResponse
	12, // 13: pb.RoboTrader.WatchDog:output_type -> pb.WatchDogResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_txgen_proto_init() }
func file_txgen_proto_init() {
	if File_txgen_proto != nil {
		return
	}
	file_txvX_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_txgen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxGenerateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxGenerateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxPublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxPublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txgen_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_txgen_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_txgen_proto_goTypes,
		DependencyIndexes: file_txgen_proto_depIdxs,
		EnumInfos:         file_txgen_proto_enumTypes,
		MessageInfos:      file_txgen_proto_msgTypes,
	}.Build()
	File_txgen_proto = out.File
	file_txgen_proto_rawDesc = nil
	file_txgen_proto_goTypes = nil
	file_txgen_proto_depIdxs = nil
}
