// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: txpin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxReceipt_TxStatus int32

const (
	TxReceipt_SUCCESSFUL TxReceipt_TxStatus = 0
	TxReceipt_FAILED     TxReceipt_TxStatus = 1
)

// Enum value maps for TxReceipt_TxStatus.
var (
	TxReceipt_TxStatus_name = map[int32]string{
		0: "SUCCESSFUL",
		1: "FAILED",
	}
	TxReceipt_TxStatus_value = map[string]int32{
		"SUCCESSFUL": 0,
		"FAILED":     1,
	}
)

func (x TxReceipt_TxStatus) Enum() *TxReceipt_TxStatus {
	p := new(TxReceipt_TxStatus)
	*p = x
	return p
}

func (x TxReceipt_TxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxReceipt_TxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_txpin_proto_enumTypes[0].Descriptor()
}

func (TxReceipt_TxStatus) Type() protoreflect.EnumType {
	return &file_txpin_proto_enumTypes[0]
}

func (x TxReceipt_TxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxReceipt_TxStatus.Descriptor instead.
func (TxReceipt_TxStatus) EnumDescriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{4, 0}
}

// SiteID - an identifier that uniquely identifies each site in dag
type SiteID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`            // uuid as bytes
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`  // hex encoded site's tx signature
	IdMajor uint64 `protobuf:"varint,3,opt,name=idMajor,proto3" json:"idMajor,omitempty"` // in dag major id position
	IdMinor uint32 `protobuf:"varint,4,opt,name=idMinor,proto3" json:"idMinor,omitempty"` // in dag minor id position (when there are collisions)
}

func (x *SiteID) Reset() {
	*x = SiteID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteID) ProtoMessage() {}

func (x *SiteID) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteID.ProtoReflect.Descriptor instead.
func (*SiteID) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{0}
}

func (x *SiteID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SiteID) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SiteID) GetIdMajor() uint64 {
	if x != nil {
		return x.IdMajor
	}
	return 0
}

func (x *SiteID) GetIdMinor() uint32 {
	if x != nil {
		return x.IdMinor
	}
	return 0
}

type Balance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance map[string][]byte `protobuf:"bytes,1,rep,name=balance,proto3" json:"balance,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // a map of wallet - balance (big.Int as []byte)
}

func (x *Balance) Reset() {
	*x = Balance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{1}
}

func (x *Balance) GetBalance() map[string][]byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

type LogTopic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *LogTopic) Reset() {
	*x = LogTopic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTopic) ProtoMessage() {}

func (x *LogTopic) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTopic.ProtoReflect.Descriptor instead.
func (*LogTopic) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{2}
}

func (x *LogTopic) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type TxExecLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractAddress []byte      `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Topics          []*LogTopic `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data            []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	PinTxNumber     int64       `protobuf:"varint,4,opt,name=pinTxNumber,proto3" json:"pinTxNumber,omitempty"`
}

func (x *TxExecLog) Reset() {
	*x = TxExecLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxExecLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxExecLog) ProtoMessage() {}

func (x *TxExecLog) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxExecLog.ProtoReflect.Descriptor instead.
func (*TxExecLog) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{3}
}

func (x *TxExecLog) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *TxExecLog) GetTopics() []*LogTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *TxExecLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TxExecLog) GetPinTxNumber() int64 {
	if x != nil {
		return x.PinTxNumber
	}
	return 0
}

type TxReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelUsed      int32              `protobuf:"varint,1,opt,name=fuelUsed,proto3" json:"fuelUsed,omitempty"`                        // used fuel for execution
	Status        TxReceipt_TxStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pb.TxReceipt_TxStatus" json:"status,omitempty"` // tx failed or successful
	StatusMessage string             `protobuf:"bytes,3,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`               // details about tx status
	Logs          []*TxExecLog       `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`                                 // logs generated during tx execution
}

func (x *TxReceipt) Reset() {
	*x = TxReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxReceipt) ProtoMessage() {}

func (x *TxReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxReceipt.ProtoReflect.Descriptor instead.
func (*TxReceipt) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{4}
}

func (x *TxReceipt) GetFuelUsed() int32 {
	if x != nil {
		return x.FuelUsed
	}
	return 0
}

func (x *TxReceipt) GetStatus() TxReceipt_TxStatus {
	if x != nil {
		return x.Status
	}
	return TxReceipt_SUCCESSFUL
}

func (x *TxReceipt) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *TxReceipt) GetLogs() []*TxExecLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type AccountData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance  []byte `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce    int64  `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Codehash []byte `protobuf:"bytes,5,opt,name=codehash,proto3" json:"codehash,omitempty"`
	Code     []byte `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AccountData) Reset() {
	*x = AccountData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountData) ProtoMessage() {}

func (x *AccountData) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountData.ProtoReflect.Descriptor instead.
func (*AccountData) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{5}
}

func (x *AccountData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccountData) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AccountData) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *AccountData) GetCodehash() []byte {
	if x != nil {
		return x.Codehash
	}
	return nil
}

func (x *AccountData) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type AccountDiff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewValue *AccountData `protobuf:"bytes,1,opt,name=newValue,proto3" json:"newValue,omitempty"`
}

func (x *AccountDiff) Reset() {
	*x = AccountDiff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDiff) ProtoMessage() {}

func (x *AccountDiff) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDiff.ProtoReflect.Descriptor instead.
func (*AccountDiff) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{6}
}

func (x *AccountDiff) GetNewValue() *AccountData {
	if x != nil {
		return x.NewValue
	}
	return nil
}

type Mapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key     []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mapping.ProtoReflect.Descriptor instead.
func (*Mapping) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{7}
}

func (x *Mapping) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Mapping) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Mapping) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Diff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to MappingOrAccount:
	//
	//	*Diff_MappingDiff
	//	*Diff_AccountDiff
	MappingOrAccount isDiff_MappingOrAccount `protobuf_oneof:"mappingOrAccount"`
}

func (x *Diff) Reset() {
	*x = Diff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff) ProtoMessage() {}

func (x *Diff) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff.ProtoReflect.Descriptor instead.
func (*Diff) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{8}
}

func (m *Diff) GetMappingOrAccount() isDiff_MappingOrAccount {
	if m != nil {
		return m.MappingOrAccount
	}
	return nil
}

func (x *Diff) GetMappingDiff() *Mapping {
	if x, ok := x.GetMappingOrAccount().(*Diff_MappingDiff); ok {
		return x.MappingDiff
	}
	return nil
}

func (x *Diff) GetAccountDiff() *AccountDiff {
	if x, ok := x.GetMappingOrAccount().(*Diff_AccountDiff); ok {
		return x.AccountDiff
	}
	return nil
}

type isDiff_MappingOrAccount interface {
	isDiff_MappingOrAccount()
}

type Diff_MappingDiff struct {
	MappingDiff *Mapping `protobuf:"bytes,1,opt,name=mappingDiff,proto3,oneof"`
}

type Diff_AccountDiff struct {
	AccountDiff *AccountDiff `protobuf:"bytes,2,opt,name=accountDiff,proto3,oneof"`
}

func (*Diff_MappingDiff) isDiff_MappingOrAccount() {}

func (*Diff_AccountDiff) isDiff_MappingOrAccount() {}

type ExecutedSmcTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx      *Txv1      `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Receipt *TxReceipt `protobuf:"bytes,3,opt,name=receipt,proto3" json:"receipt,omitempty"`
}

func (x *ExecutedSmcTx) Reset() {
	*x = ExecutedSmcTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutedSmcTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedSmcTx) ProtoMessage() {}

func (x *ExecutedSmcTx) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedSmcTx.ProtoReflect.Descriptor instead.
func (*ExecutedSmcTx) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutedSmcTx) GetTx() *Txv1 {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *ExecutedSmcTx) GetReceipt() *TxReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// ValidatorSignature - one validator's signature over a commit transaction's
// prototype hash (TxPin.PrototypeHash), which excludes the signatures
// themselves so that every validator signs the same bytes.
type ValidatorSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pk   []byte `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`     // the validator's public key
	Sign []byte `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"` // signature over the prototype hash
}

func (x *ValidatorSignature) Reset() {
	*x = ValidatorSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSignature) ProtoMessage() {}

func (x *ValidatorSignature) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSignature.ProtoReflect.Descriptor instead.
func (*ValidatorSignature) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{10}
}

func (x *ValidatorSignature) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *ValidatorSignature) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

// QuorumCert - evidence that a quorum of the validator set agreed to this exact
// commit transaction. Replaces "the leader said so" as the reason a node applies
// one.
type QuorumCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PinNumber  int64                 `protobuf:"varint,1,opt,name=pinNumber,proto3" json:"pinNumber,omitempty"` // which commit transaction this certifies
	PinHash    []byte                `protobuf:"bytes,2,opt,name=pinHash,proto3" json:"pinHash,omitempty"`      // the prototype hash the validators signed
	Round      uint32                `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`         // the view-change round agreement was reached in
	Signatures []*ValidatorSignature `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{11}
}

func (x *QuorumCert) GetPinNumber() int64 {
	if x != nil {
		return x.PinNumber
	}
	return 0
}

func (x *QuorumCert) GetPinHash() []byte {
	if x != nil {
		return x.PinHash
	}
	return nil
}

func (x *QuorumCert) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *QuorumCert) GetSignatures() []*ValidatorSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// TxPin - pinning transaction definition
// RewardRecord - one processor's cut of a commit transaction's fees.
//
// The weight is carried rather than re-derived: a node checking the split later
// cannot recover the balance the weight was computed from, because the balance
// has since moved. Amounts are big-endian bytes, not an integer field, because
// a fee total does not fit in 64 bits at every possible parameter setting and
// must not be silently truncated on the way to somebody's wallet.
type RewardRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processor   []byte `protobuf:"bytes,1,opt,name=processor,proto3" json:"processor,omitempty"`      // the account paid
	Work        uint32 `protobuf:"varint,2,opt,name=work,proto3" json:"work,omitempty"`               // sites in this commit transaction attributed to it
	WeightMilli uint32 `protobuf:"varint,3,opt,name=weightMilli,proto3" json:"weightMilli,omitempty"` // the stake weight applied, in permille
	Amount      []byte `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`            // the reward, big-endian
}

func (x *RewardRecord) Reset() {
	*x = RewardRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardRecord) ProtoMessage() {}

func (x *RewardRecord) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardRecord.ProtoReflect.Descriptor instead.
func (*RewardRecord) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{12}
}

func (x *RewardRecord) GetProcessor() []byte {
	if x != nil {
		return x.Processor
	}
	return nil
}

func (x *RewardRecord) GetWork() uint32 {
	if x != nil {
		return x.Work
	}
	return 0
}

func (x *RewardRecord) GetWeightMilli() uint32 {
	if x != nil {
		return x.WeightMilli
	}
	return 0
}

func (x *RewardRecord) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type TxPin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prev      []byte                 `protobuf:"bytes,1,opt,name=prev,proto3" json:"prev,omitempty"`       // prev pin tx id
	Ts        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`           // timestamp when the tx was created
	Sites     []*SiteID              `protobuf:"bytes,3,rep,name=sites,proto3" json:"sites,omitempty"`     // a collection of site ids (a list of fully confirmed sites in the current slice)
	Nodes     []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`     // sites included in this pin tx
	Balance   *Balance               `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"` // all balances for all the tx in teh current pinning tx
	Pk        []byte                 `protobuf:"bytes,6,opt,name=pk,proto3" json:"pk,omitempty"`           // public key to verify this pin tx signature
	Sign      []byte                 `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`       // this pin tx signature
	SmcTxs    []*ExecutedSmcTx       `protobuf:"bytes,8,rep,name=smcTxs,proto3" json:"smcTxs,omitempty"`   // executed smart contract transactions within this pin tx
	Diffs     []*Diff                `protobuf:"bytes,9,rep,name=diffs,proto3" json:"diffs,omitempty"`     // diffs on smart contract state store appeared after executing smart contract transactions
	PinNumber int64                  `protobuf:"varint,10,opt,name=pinNumber,proto3" json:"pinNumber,omitempty"`
	Quorum    *QuorumCert            `protobuf:"bytes,11,opt,name=quorum,proto3" json:"quorum,omitempty"`     // a quorum of validators agreed this pin; absent in single-leader mode
	Proposer  []byte                 `protobuf:"bytes,12,opt,name=proposer,proto3" json:"proposer,omitempty"` // the validator that built it
	// The fee split, recomputable by every node from the fields above it. See
	// docs/economics.md. Absent while fees are off, which is the default, so a
	// commit transaction from a node with fees disabled encodes exactly as it
	// did before these fields existed.
	FeePool      []byte          `protobuf:"bytes,13,opt,name=feePool,proto3" json:"feePool,omitempty"`           // total fees this commit transaction collected, big-endian
	Rewards      []*RewardRecord `protobuf:"bytes,14,rep,name=rewards,proto3" json:"rewards,omitempty"`           // who is paid what, ordered by account
	FeeRemainder []byte          `protobuf:"bytes,15,opt,name=feeRemainder,proto3" json:"feeRemainder,omitempty"` // what floor division left over, paid to coinbase
	Coinbase     []byte          `protobuf:"bytes,16,opt,name=coinbase,proto3" json:"coinbase,omitempty"`         // the account the remainder went to
}

func (x *TxPin) Reset() {
	*x = TxPin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPin) ProtoMessage() {}

func (x *TxPin) ProtoReflect() protoreflect.Message {
	mi := &file_txpin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPin.ProtoReflect.Descriptor instead.
func (*TxPin) Descriptor() ([]byte, []int) {
	return file_txpin_proto_rawDescGZIP(), []int{13}
}

func (x *TxPin) GetPrev() []byte {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *TxPin) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TxPin) GetSites() []*SiteID {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *TxPin) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TxPin) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *TxPin) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *TxPin) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *TxPin) GetSmcTxs() []*ExecutedSmcTx {
	if x != nil {
		return x.SmcTxs
	}
	return nil
}

func (x *TxPin) GetDiffs() []*Diff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

func (x *TxPin) GetPinNumber() int64 {
	if x != nil {
		return x.PinNumber
	}
	return 0
}

func (x *TxPin) GetQuorum() *QuorumCert {
	if x != nil {
		return x.Quorum
	}
	return nil
}

func (x *TxPin) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *TxPin) GetFeePool() []byte {
	if x != nil {
		return x.FeePool
	}
	return nil
}

func (x *TxPin) GetRewards() []*RewardRecord {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *TxPin) GetFeeRemainder() []byte {
	if x != nil {
		return x.FeeRemainder
	}
	return nil
}

func (x *TxPin) GetCoinbase() []byte {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

var File_txpin_proto protoreflect.FileDescriptor

var file_txpin_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x78, 0x70, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x74, 0x78, 0x76, 0x58, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x06, 0x53, 0x69,
	0x74, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x64, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x69, 0x64, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x4d, 0x69,
	0x6e, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x64, 0x4d, 0x69, 0x6e,
	0x6f, 0x72, 0x22, 0x79, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1e, 0x0a,
	0x08, 0x4c, 0x6f, 0x67, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x91, 0x01,
	0x0a, 0x09, 0x54, 0x78, 0x45, 0x78, 0x65, 0x63, 0x4c, 0x6f, 0x67, 0x12, 0x28, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x69, 0x6e, 0x54, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x69, 0x6e, 0x54, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0xc8, 0x01, 0x0a, 0x09, 0x54, 0x78, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x75, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x66, 0x75, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x78, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x54, 0x78, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x21, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x45, 0x78, 0x65, 0x63, 0x4c, 0x6f, 0x67, 0x52, 0x04,
	0x6c, 0x6f, 0x67, 0x73, 0x22, 0x26, 0x0a, 0x08, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x46, 0x55, 0x4c, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x22, 0x87, 0x01, 0x0a,
	0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x44, 0x69, 0x66, 0x66, 0x12, 0x2b, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x06, 0x22, 0x4b, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x04, 0x44, 0x69, 0x66, 0x66, 0x12, 0x2f,
	0x0a, 0x0b, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x66, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x48, 0x00, 0x52, 0x0b, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x66, 0x66, 0x12,
	0x33, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x69, 0x66, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x44, 0x69, 0x66, 0x66, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x44, 0x69, 0x66, 0x66, 0x42, 0x12, 0x0a, 0x10, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x4f,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x52, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x64, 0x53, 0x6d, 0x63, 0x54, 0x78, 0x12, 0x18, 0x0a, 0x02, 0x74, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x76, 0x31, 0x52,
	0x02, 0x74, 0x78, 0x12, 0x27, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x38, 0x0a, 0x12,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x70, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x92, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x72, 0x75,
	0x6d, 0x43, 0x65, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x69, 0x6e, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x69, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x12, 0x36, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x7a, 0x0a, 0x0c, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x20, 0x0a,
	0x0b, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x87, 0x04, 0x0a, 0x05, 0x54, 0x78, 0x50, 0x69,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x65, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x70, 0x72, 0x65, 0x76, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74,
	0x73, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x69, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x49, 0x44, 0x52, 0x05, 0x73, 0x69,
	0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x67, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x29,
	0x0a, 0x06, 0x73, 0x6d, 0x63, 0x54, 0x78, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x53, 0x6d, 0x63, 0x54,
	0x78, 0x52, 0x06, 0x73, 0x6d, 0x63, 0x54, 0x78, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x64, 0x69, 0x66,
	0x66, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69,
	0x66, 0x66, 0x52, 0x05, 0x64, 0x69, 0x66, 0x66, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x69, 0x6e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x69,
	0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x72, 0x75,
	0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f,
	0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x06, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x65, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x66, 0x65,
	0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x66, 0x65, 0x65, 0x52, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73,
	0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_txpin_proto_rawDescOnce sync.Once
	file_txpin_proto_rawDescData = file_txpin_proto_rawDesc
)

func file_txpin_proto_rawDescGZIP() []byte {
	file_txpin_proto_rawDescOnce.Do(func() {
		file_txpin_proto_rawDescData = protoimpl.X.CompressGZIP(file_txpin_proto_rawDescData)
	})
	return file_txpin_proto_rawDescData
}

var file_txpin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_txpin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_txpin_proto_goTypes = []interface{}{
	(TxReceipt_TxStatus)(0),       // 0: pb.TxReceipt.TxStatus
	(*SiteID)(nil),                // 1: pb.SiteID
	(*Balance)(nil),               // 2: pb.Balance
	(*LogTopic)(nil),              // 3: pb.LogTopic
	(*TxExecLog)(nil),             // 4: pb.TxExecLog
	(*TxReceipt)(nil),             // 5: pb.TxReceipt
	(*AccountData)(nil),           // 6: pb.AccountData
	(*AccountDiff)(nil),           // 7: pb.AccountDiff
	(*Mapping)(nil),               // 8: pb.Mapping
	(*Diff)(nil),                  // 9: pb.Diff
	(*ExecutedSmcTx)(nil),         // 10: pb.ExecutedSmcTx
	(*ValidatorSignature)(nil),    // 11: pb.ValidatorSignature
	(*QuorumCert)(nil),            // 12: pb.QuorumCert
	(*RewardRecord)(nil),          // 13: pb.RewardRecord
	(*TxPin)(nil),                 // 14: pb.TxPin
	nil,                           // 15: pb.Balance.BalanceEntry
	(*Txv1)(nil),                  // 16: pb.Txv1
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*Node)(nil),                  // 18: pb.Node
}
var file_txpin_proto_depIdxs = []int32{
	15, // 0: pb.Balance.balance:type_name -> pb.Balance.BalanceEntry
	3,  // 1: pb.TxExecLog.topics:type_name -> pb.LogTopic
	0,  // 2: pb.TxReceipt.status:type_name -> pb.TxReceipt.TxStatus
	4,  // 3: pb.TxReceipt.logs:type_name -> pb.TxExecLog
	6,  // 4: pb.AccountDiff.newValue:type_name -> pb.AccountData
	8,  // 5: pb.Diff.mappingDiff:type_name -> pb.Mapping
	7,  // 6: pb.Diff.accountDiff:type_name -> pb.AccountDiff
	16, // 7: pb.ExecutedSmcTx.tx:type_name -> pb.Txv1
	5,  // 8: pb.ExecutedSmcTx.receipt:type_name -> pb.TxReceipt
	11, // 9: pb.QuorumCert.signatures:type_name -> pb.ValidatorSignature
	17, // 10: pb.TxPin.ts:type_name -> google.protobuf.Timestamp
	1,  // 11: pb.TxPin.sites:type_name -> pb.SiteID
	18, // 12: pb.TxPin.nodes:type_name -> pb.Node
	2,  // 13: pb.TxPin.balance:type_name -> pb.Balance
	10, // 14: pb.TxPin.smcTxs:type_name -> pb.ExecutedSmcTx
	9,  // 15: pb.TxPin.diffs:type_name -> pb.Diff
	12, // 16: pb.TxPin.quorum:type_name -> pb.QuorumCert
	13, // 17: pb.TxPin.rewards:type_name -> pb.RewardRecord
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_txpin_proto_init() }
func file_txpin_proto_init() {
	if File_txpin_proto != nil {
		return
	}
	file_node_proto_init()
	file_txvX_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_txpin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Balance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogTopic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxExecLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDiff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutedSmcTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuorumCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewardRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxPin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_txpin_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Diff_MappingDiff)(nil),
		(*Diff_AccountDiff)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_txpin_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txpin_proto_goTypes,
		DependencyIndexes: file_txpin_proto_depIdxs,
		EnumInfos:         file_txpin_proto_enumTypes,
		MessageInfos:      file_txpin_proto_msgTypes,
	}.Build()
	File_txpin_proto = out.File
	file_txpin_proto_rawDesc = nil
	file_txpin_proto_goTypes = nil
	file_txpin_proto_depIdxs = nil
}
