// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: txvX.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_PAYMENT          TransactionType = 0
	TransactionType_PUBLISH_CONTRACT TransactionType = 1
	TransactionType_CALL_CONTRACT    TransactionType = 2
	TransactionType_SERVICE_GENESIS  TransactionType = 3
	TransactionType_SERVICE          TransactionType = 4
	TransactionType_SERVICE_PIN      TransactionType = 5
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "PAYMENT",
		1: "PUBLISH_CONTRACT",
		2: "CALL_CONTRACT",
		3: "SERVICE_GENESIS",
		4: "SERVICE",
		5: "SERVICE_PIN",
	}
	TransactionType_value = map[string]int32{
		"PAYMENT":          0,
		"PUBLISH_CONTRACT": 1,
		"CALL_CONTRACT":    2,
		"SERVICE_GENESIS":  3,
		"SERVICE":          4,
		"SERVICE_PIN":      5,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_txvX_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_txvX_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_txvX_proto_rawDescGZIP(), []int{0}
}

type ChainType int32

const (
	ChainType_MAINNET         ChainType = 0
	ChainType_PUBLIC_TESTNET  ChainType = 1
	ChainType_PRIVATE_TESTNET ChainType = 2
)

// Enum value maps for ChainType.
var (
	ChainType_name = map[int32]string{
		0: "MAINNET",
		1: "PUBLIC_TESTNET",
		2: "PRIVATE_TESTNET",
	}
	ChainType_value = map[string]int32{
		"MAINNET":         0,
		"PUBLIC_TESTNET":  1,
		"PRIVATE_TESTNET": 2,
	}
)

func (x ChainType) Enum() *ChainType {
	p := new(ChainType)
	*p = x
	return p
}

func (x ChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_txvX_proto_enumTypes[1].Descriptor()
}

func (ChainType) Type() protoreflect.EnumType {
	return &file_txvX_proto_enumTypes[1]
}

func (x ChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainType.Descriptor instead.
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return file_txvX_proto_rawDescGZIP(), []int{1}
}

type VersionType int32

const (
	VersionType_TXV0 VersionType = 0
	VersionType_TXV1 VersionType = 1
)

// Enum value maps for VersionType.
var (
	VersionType_name = map[int32]string{
		0: "TXV0",
		1: "TXV1",
	}
	VersionType_value = map[string]int32{
		"TXV0": 0,
		"TXV1": 1,
	}
)

func (x VersionType) Enum() *VersionType {
	p := new(VersionType)
	*p = x
	return p
}

func (x VersionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionType) Descriptor() protoreflect.EnumDescriptor {
	return file_txvX_proto_enumTypes[2].Descriptor()
}

func (VersionType) Type() protoreflect.EnumType {
	return &file_txvX_proto_enumTypes[2]
}

func (x VersionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionType.Descriptor instead.
func (VersionType) EnumDescriptor() ([]byte, []int) {
	return file_txvX_proto_rawDescGZIP(), []int{2}
}

type Txv1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxType     TransactionType        `protobuf:"varint,1,opt,name=tx_type,json=txType,proto3,enum=pb.TransactionType" json:"tx_type,omitempty"`
	ChainType  ChainType              `protobuf:"varint,2,opt,name=chain_type,json=chainType,proto3,enum=pb.ChainType" json:"chain_type,omitempty"`
	SenderPubk []byte                 `protobuf:"bytes,4,opt,name=sender_pubk,json=senderPubk,proto3" json:"sender_pubk,omitempty"` // sender's public key: secp256k1
	Sender     []byte                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`                           // sender's wallet address
	Recepient  []byte                 `protobuf:"bytes,6,opt,name=recepient,proto3" json:"recepient,omitempty"`                     // recipient’s wallet address
	Amount     []byte                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce      uint64                 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FuelLimit  []byte                 `protobuf:"bytes,10,opt,name=fuel_limit,json=fuelLimit,proto3" json:"fuel_limit,omitempty"`
	FuelPrice  []byte                 `protobuf:"bytes,11,opt,name=fuel_price,json=fuelPrice,proto3" json:"fuel_price,omitempty"`
	Data       []byte                 `protobuf:"bytes,12,opt,name=data,proto3,oneof" json:"data,omitempty"`     // optional for payments; mandatory for contracts
	Signature  []byte                 `protobuf:"bytes,13,opt,name=signature,proto3" json:"signature,omitempty"` // Signature of the serialized transaction bytes signed by user’s private key
	RlpEthTx   []byte                 `protobuf:"bytes,14,opt,name=rlpEthTx,proto3" json:"rlpEthTx,omitempty"`   // original bytes of the eth rlp tx
}

func (x *Txv1) Reset() {
	*x = Txv1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txvX_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txv1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txv1) ProtoMessage() {}

func (x *Txv1) ProtoReflect() protoreflect.Message {
	mi := &file_txvX_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txv1.ProtoReflect.Descriptor instead.
func (*Txv1) Descriptor() ([]byte, []int) {
	return file_txvX_proto_rawDescGZIP(), []int{0}
}

func (x *Txv1) GetTxType() TransactionType {
	if x != nil {
		return x.TxType
	}
	return TransactionType_PAYMENT
}

func (x *Txv1) GetChainType() ChainType {
	if x != nil {
		return x.ChainType
	}
	return ChainType_MAINNET
}

func (x *Txv1) GetSenderPubk() []byte {
	if x != nil {
		return x.SenderPubk
	}
	return nil
}

func (x *Txv1) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Txv1) GetRecepient() []byte {
	if x != nil {
		return x.Recepient
	}
	return nil
}

func (x *Txv1) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Txv1) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Txv1) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Txv1) GetFuelLimit() []byte {
	if x != nil {
		return x.FuelLimit
	}
	return nil
}

func (x *Txv1) GetFuelPrice() []byte {
	if x != nil {
		return x.FuelPrice
	}
	return nil
}

func (x *Txv1) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Txv1) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Txv1) GetRlpEthTx() []byte {
	if x != nil {
		return x.RlpEthTx
	}
	return nil
}

type Txv2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Txv2) Reset() {
	*x = Txv2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txvX_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txv2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txv2) ProtoMessage() {}

func (x *Txv2) ProtoReflect() protoreflect.Message {
	mi := &file_txvX_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txv2.ProtoReflect.Descriptor instead.
func (*Txv2) Descriptor() ([]byte, []int) {
	return file_txvX_proto_rawDescGZIP(), []int{1}
}

var File_txvX_proto protoreflect.FileDescriptor

var file_txvX_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x78, 0x76, 0x58, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc7, 0x03, 0x0a, 0x04, 0x54, 0x78, 0x76, 0x31, 0x12, 0x2c, 0x0a, 0x07, 0x74, 0x78,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x06, 0x74, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x70, 0x75, 0x62, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x66, 0x75, 0x65, 0x6c, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x66, 0x75, 0x65, 0x6c, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6c,
	0x70, 0x45, 0x74, 0x68, 0x54, 0x78, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x6c,
	0x70, 0x45, 0x74, 0x68, 0x54, 0x78, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x4a,
	0x04, 0x08, 0x03, 0x10, 0x04, 0x4a, 0x04, 0x08, 0x0f, 0x10, 0x10, 0x22, 0x0c, 0x0a, 0x04, 0x54,
	0x78, 0x76, 0x32, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x10, 0x2a, 0x80, 0x01, 0x0a, 0x0f, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x53, 0x48, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x41, 0x43, 0x54, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x41, 0x4c, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x41, 0x43,
	0x54, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x47,
	0x45, 0x4e, 0x45, 0x53, 0x49, 0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52, 0x56,
	0x49, 0x43, 0x45, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x50, 0x49, 0x4e, 0x10, 0x05, 0x22, 0x04, 0x08, 0x06, 0x10, 0x0f, 0x2a, 0x47, 0x0a, 0x09,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x49,
	0x4e, 0x4e, 0x45, 0x54, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43,
	0x5f, 0x54, 0x45, 0x53, 0x54, 0x4e, 0x45, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52,
	0x49, 0x56, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x4e, 0x45, 0x54, 0x10, 0x02, 0x22,
	0x04, 0x08, 0x03, 0x10, 0x0f, 0x2a, 0x27, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x58, 0x56, 0x30, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x54, 0x58, 0x56, 0x31, 0x10, 0x01, 0x22, 0x04, 0x08, 0x02, 0x10, 0x0f, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_txvX_proto_rawDescOnce sync.Once
	file_txvX_proto_rawDescData = file_txvX_proto_rawDesc
)

func file_txvX_proto_rawDescGZIP() []byte {
	file_txvX_proto_rawDescOnce.Do(func() {
		file_txvX_proto_rawDescData = protoimpl.X.CompressGZIP(file_txvX_proto_rawDescData)
	})
	return file_txvX_proto_rawDescData
}

var file_txvX_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_txvX_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_txvX_proto_goTypes = []interface{}{
	(TransactionType)(0),          // 0: pb.TransactionType
	(ChainType)(0),                // 1: pb.ChainType
	(VersionType)(0),              // 2: pb.VersionType
	(*Txv1)(nil),                  // 3: pb.Txv1
	(*Txv2)(nil),                  // 4: pb.Txv2
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_txvX_proto_depIdxs = []int32{
	0, // 0: pb.Txv1.tx_type:type_name -> pb.TransactionType
	1, // 1: pb.Txv1.chain_type:type_name -> pb.ChainType
	5, // 2: pb.Txv1.timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_txvX_proto_init() }
func file_txvX_proto_init() {
	if File_txvX_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_txvX_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txv1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txvX_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txv2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_txvX_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_txvX_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txvX_proto_goTypes,
		DependencyIndexes: file_txvX_proto_depIdxs,
		EnumInfos:         file_txvX_proto_enumTypes,
		MessageInfos:      file_txvX_proto_msgTypes,
	}.Build()
	File_txvX_proto = out.File
	file_txvX_proto_rawDesc = nil
	file_txvX_proto_goTypes = nil
	file_txvX_proto_depIdxs = nil
}
