// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: vertex.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vertex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VertexId  *Vertex_VertexId       `protobuf:"bytes,1,opt,name=vertexId,proto3" json:"vertexId,omitempty"`
	CumWeight float64                `protobuf:"fixed64,2,opt,name=cumWeight,proto3" json:"cumWeight,omitempty"`
	TxWeight  float64                `protobuf:"fixed64,3,opt,name=txWeight,proto3" json:"txWeight,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tx        *Txv1                  `protobuf:"bytes,5,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vertex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_vertex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_vertex_proto_rawDescGZIP(), []int{0}
}

func (x *Vertex) GetVertexId() *Vertex_VertexId {
	if x != nil {
		return x.VertexId
	}
	return nil
}

func (x *Vertex) GetCumWeight() float64 {
	if x != nil {
		return x.CumWeight
	}
	return 0
}

func (x *Vertex) GetTxWeight() float64 {
	if x != nil {
		return x.TxWeight
	}
	return 0
}

func (x *Vertex) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Vertex) GetTx() *Txv1 {
	if x != nil {
		return x.Tx
	}
	return nil
}

type Vertex_VertexId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	IdMajor uint64 `protobuf:"varint,3,opt,name=idMajor,proto3" json:"idMajor,omitempty"`
	IdMinor uint32 `protobuf:"varint,4,opt,name=idMinor,proto3" json:"idMinor,omitempty"`
}

func (x *Vertex_VertexId) Reset() {
	*x = Vertex_VertexId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vertex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vertex_VertexId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex_VertexId) ProtoMessage() {}

func (x *Vertex_VertexId) ProtoReflect() protoreflect.Message {
	mi := &file_vertex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex_VertexId.ProtoReflect.Descriptor instead.
func (*Vertex_VertexId) Descriptor() ([]byte, []int) {
	return file_vertex_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Vertex_VertexId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Vertex_VertexId) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Vertex_VertexId) GetIdMajor() uint64 {
	if x != nil {
		return x.IdMajor
	}
	return 0
}

func (x *Vertex_VertexId) GetIdMinor() uint32 {
	if x != nil {
		return x.IdMinor
	}
	return 0
}

var File_vertex_proto protoreflect.FileDescriptor

var file_vertex_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x74, 0x78, 0x76, 0x58, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb1, 0x02, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x12, 0x2f, 0x0a, 0x08, 0x76, 0x65,
	0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49,
	0x64, 0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x75, 0x6d, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x63, 0x75, 0x6d, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x78, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x74, 0x78, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x18, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x78, 0x76, 0x31, 0x52, 0x02, 0x74, 0x78, 0x1a, 0x68, 0x0a, 0x08, 0x56, 0x65, 0x72,
	0x74, 0x65, 0x78, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x64, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x69, 0x64, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x4d,
	0x69, 0x6e, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x64, 0x4d, 0x69,
	0x6e, 0x6f, 0x72, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_vertex_proto_rawDescOnce sync.Once
	file_vertex_proto_rawDescData = file_vertex_proto_rawDesc
)

func file_vertex_proto_rawDescGZIP() []byte {
	file_vertex_proto_rawDescOnce.Do(func() {
		file_vertex_proto_rawDescData = protoimpl.X.CompressGZIP(file_vertex_proto_rawDescData)
	})
	return file_vertex_proto_rawDescData
}

var file_vertex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vertex_proto_goTypes = []interface{}{
	(*Vertex)(nil),                // 0: pb.Vertex
	(*Vertex_VertexId)(nil),       // 1: pb.Vertex.VertexId
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Txv1)(nil),                  // 3: pb.Txv1
}
var file_vertex_proto_depIdxs = []int32{
	1, // 0: pb.Vertex.vertexId:type_name -> pb.Vertex.VertexId
	2, // 1: pb.Vertex.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: pb.Vertex.tx:type_name -> pb.Txv1
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vertex_proto_init() }
func file_vertex_proto_init() {
	if File_vertex_proto != nil {
		return
	}
	file_txvX_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vertex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vertex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vertex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vertex_VertexId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vertex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vertex_proto_goTypes,
		DependencyIndexes: file_vertex_proto_depIdxs,
		MessageInfos:      file_vertex_proto_msgTypes,
	}.Build()
	File_vertex_proto = out.File
	file_vertex_proto_rawDesc = nil
	file_vertex_proto_goTypes = nil
	file_vertex_proto_depIdxs = nil
}
