// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: vm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SCVmServiceClient is the client API for SCVmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SCVmServiceClient interface {
	RunCall(ctx context.Context, in *WriteContractRequest, opts ...grpc.CallOption) (*CallResponse, error)
	RunCode(ctx context.Context, in *ReadContractRequest, opts ...grpc.CallOption) (*CallResponse, error)
	EstimateGas(ctx context.Context, in *EstimateGasRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type sCVmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSCVmServiceClient(cc grpc.ClientConnInterface) SCVmServiceClient {
	return &sCVmServiceClient{cc}
}

func (c *sCVmServiceClient) RunCall(ctx context.Context, in *WriteContractRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/pb.SCVmService/runCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sCVmServiceClient) RunCode(ctx context.Context, in *ReadContractRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/pb.SCVmService/runCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sCVmServiceClient) EstimateGas(ctx context.Context, in *EstimateGasRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/pb.SCVmService/estimateGas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SCVmServiceServer is the server API for SCVmService service.
// All implementations must embed UnimplementedSCVmServiceServer
// for forward compatibility
type SCVmServiceServer interface {
	RunCall(context.Context, *WriteContractRequest) (*CallResponse, error)
	RunCode(context.Context, *ReadContractRequest) (*CallResponse, error)
	EstimateGas(context.Context, *EstimateGasRequest) (*CallResponse, error)
	mustEmbedUnimplementedSCVmServiceServer()
}

// UnimplementedSCVmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSCVmServiceServer struct {
}

func (UnimplementedSCVmServiceServer) RunCall(context.Context, *WriteContractRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCall not implemented")
}
func (UnimplementedSCVmServiceServer) RunCode(context.Context, *ReadContractRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCode not implemented")
}
func (UnimplementedSCVmServiceServer) EstimateGas(context.Context, *EstimateGasRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateGas not implemented")
}
func (UnimplementedSCVmServiceServer) mustEmbedUnimplementedSCVmServiceServer() {}

// UnsafeSCVmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SCVmServiceServer will
// result in compilation errors.
type UnsafeSCVmServiceServer interface {
	mustEmbedUnimplementedSCVmServiceServer()
}

func RegisterSCVmServiceServer(s grpc.ServiceRegistrar, srv SCVmServiceServer) {
	s.RegisterService(&SCVmService_ServiceDesc, srv)
}

func _SCVmService_RunCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCVmServiceServer).RunCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SCVmService/runCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCVmServiceServer).RunCall(ctx, req.(*WriteContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SCVmService_RunCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCVmServiceServer).RunCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SCVmService/runCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCVmServiceServer).RunCode(ctx, req.(*ReadContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SCVmService_EstimateGas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateGasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCVmServiceServer).EstimateGas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SCVmService/estimateGas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCVmServiceServer).EstimateGas(ctx, req.(*EstimateGasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SCVmService_ServiceDesc is the grpc.ServiceDesc for SCVmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SCVmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SCVmService",
	HandlerType: (*SCVmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "runCall",
			Handler:    _SCVmService_RunCall_Handler,
		},
		{
			MethodName: "runCode",
			Handler:    _SCVmService_RunCode_Handler,
		},
		{
			MethodName: "estimateGas",
			Handler:    _SCVmService_EstimateGas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

// NodeStorageServiceClient is the client API for NodeStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeStorageServiceClient interface {
	GetAccount(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Account, error)
	CreateAccount(ctx context.Context, in *Address, opts ...grpc.CallOption) (*OpResult, error)
	PutContractCode(ctx context.Context, in *PutContractCodeRequest, opts ...grpc.CallOption) (*OpResult, error)
	AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*OpResult, error)
	SubBalance(ctx context.Context, in *SubBalanceRequest, opts ...grpc.CallOption) (*OpResult, error)
	GetContractCode(ctx context.Context, in *Address, opts ...grpc.CallOption) (*ContractCode, error)
	GetContractCodeStorage(ctx context.Context, in *GetFromStorageByKeyRequest, opts ...grpc.CallOption) (*Value, error)
	PutContractStorage(ctx context.Context, in *PutIntoStorageRequest, opts ...grpc.CallOption) (*OpResult, error)
	StateCheckpoint(ctx context.Context, in *TransactionalRequest, opts ...grpc.CallOption) (*OpResult, error)
	StateCommit(ctx context.Context, in *TransactionalRequest, opts ...grpc.CallOption) (*OpResult, error)
	StateRevert(ctx context.Context, in *TransactionalRequest, opts ...grpc.CallOption) (*OpResult, error)
	SetNonce(ctx context.Context, in *SetNonceRequest, opts ...grpc.CallOption) (*OpResult, error)
	SaveLogs(ctx context.Context, in *SaveLogsRequest, opts ...grpc.CallOption) (*OpResult, error)
	DumpState(ctx context.Context, in *DumpStateRequest, opts ...grpc.CallOption) (*DumpStateResponse, error)
}

type nodeStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeStorageServiceClient(cc grpc.ClientConnInterface) NodeStorageServiceClient {
	return &nodeStorageServiceClient{cc}
}

func (c *nodeStorageServiceClient) GetAccount(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/getAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) CreateAccount(ctx context.Context, in *Address, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/createAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) PutContractCode(ctx context.Context, in *PutContractCodeRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/putContractCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/addBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) SubBalance(ctx context.Context, in *SubBalanceRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/subBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) GetContractCode(ctx context.Context, in *Address, opts ...grpc.CallOption) (*ContractCode, error) {
	out := new(ContractCode)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/getContractCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) GetContractCodeStorage(ctx context.Context, in *GetFromStorageByKeyRequest, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/getContractCodeStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) PutContractStorage(ctx context.Context, in *PutIntoStorageRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/putContractStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) StateCheckpoint(ctx context.Context, in *TransactionalRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/stateCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) StateCommit(ctx context.Context, in *TransactionalRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/stateCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) StateRevert(ctx context.Context, in *TransactionalRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/stateRevert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) SetNonce(ctx context.Context, in *SetNonceRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/setNonce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) SaveLogs(ctx context.Context, in *SaveLogsRequest, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/saveLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStorageServiceClient) DumpState(ctx context.Context, in *DumpStateRequest, opts ...grpc.CallOption) (*DumpStateResponse, error) {
	out := new(DumpStateResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeStorageService/dumpState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeStorageServiceServer is the server API for NodeStorageService service.
// All implementations must embed UnimplementedNodeStorageServiceServer
// for forward compatibility
type NodeStorageServiceServer interface {
	GetAccount(context.Context, *Address) (*Account, error)
	CreateAccount(context.Context, *Address) (*OpResult, error)
	PutContractCode(context.Context, *PutContractCodeRequest) (*OpResult, error)
	AddBalance(context.Context, *AddBalanceRequest) (*OpResult, error)
	SubBalance(context.Context, *SubBalanceRequest) (*OpResult, error)
	GetContractCode(context.Context, *Address) (*ContractCode, error)
	GetContractCodeStorage(context.Context, *GetFromStorageByKeyRequest) (*Value, error)
	PutContractStorage(context.Context, *PutIntoStorageRequest) (*OpResult, error)
	StateCheckpoint(context.Context, *TransactionalRequest) (*OpResult, error)
	StateCommit(context.Context, *TransactionalRequest) (*OpResult, error)
	StateRevert(context.Context, *TransactionalRequest) (*OpResult, error)
	SetNonce(context.Context, *SetNonceRequest) (*OpResult, error)
	SaveLogs(context.Context, *SaveLogsRequest) (*OpResult, error)
	DumpState(context.Context, *DumpStateRequest) (*DumpStateResponse, error)
	mustEmbedUnimplementedNodeStorageServiceServer()
}

// UnimplementedNodeStorageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeStorageServiceServer struct {
}

func (UnimplementedNodeStorageServiceServer) GetAccount(context.Context, *Address) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedNodeStorageServiceServer) CreateAccount(context.Context, *Address) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedNodeStorageServiceServer) PutContractCode(context.Context, *PutContractCodeRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutContractCode not implemented")
}
func (UnimplementedNodeStorageServiceServer) AddBalance(context.Context, *AddBalanceRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBalance not implemented")
}
func (UnimplementedNodeStorageServiceServer) SubBalance(context.Context, *SubBalanceRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubBalance not implemented")
}
func (UnimplementedNodeStorageServiceServer) GetContractCode(context.Context, *Address) (*ContractCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractCode not implemented")
}
func (UnimplementedNodeStorageServiceServer) GetContractCodeStorage(context.Context, *GetFromStorageByKeyRequest) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractCodeStorage not implemented")
}
func (UnimplementedNodeStorageServiceServer) PutContractStorage(context.Context, *PutIntoStorageRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutContractStorage not implemented")
}
func (UnimplementedNodeStorageServiceServer) StateCheckpoint(context.Context, *TransactionalRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StateCheckpoint not implemented")
}
func (UnimplementedNodeStorageServiceServer) StateCommit(context.Context, *TransactionalRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StateCommit not implemented")
}
func (UnimplementedNodeStorageServiceServer) StateRevert(context.Context, *TransactionalRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StateRevert not implemented")
}
func (UnimplementedNodeStorageServiceServer) SetNonce(context.Context, *SetNonceRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNonce not implemented")
}
func (UnimplementedNodeStorageServiceServer) SaveLogs(context.Context, *SaveLogsRequest) (*OpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLogs not implemented")
}
func (UnimplementedNodeStorageServiceServer) DumpState(context.Context, *DumpStateRequest) (*DumpStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpState not implemented")
}
func (UnimplementedNodeStorageServiceServer) mustEmbedUnimplementedNodeStorageServiceServer() {}

// UnsafeNodeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeStorageServiceServer will
// result in compilation errors.
type UnsafeNodeStorageServiceServer interface {
	mustEmbedUnimplementedNodeStorageServiceServer()
}

func RegisterNodeStorageServiceServer(s grpc.ServiceRegistrar, srv NodeStorageServiceServer) {
	s.RegisterService(&NodeStorageService_ServiceDesc, srv)
}

func _NodeStorageService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/getAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).GetAccount(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/createAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).CreateAccount(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_PutContractCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutContractCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).PutContractCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/putContractCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).PutContractCode(ctx, req.(*PutContractCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_AddBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).AddBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/addBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).AddBalance(ctx, req.(*AddBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_SubBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).SubBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/subBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).SubBalance(ctx, req.(*SubBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_GetContractCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).GetContractCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/getContractCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).GetContractCode(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_GetContractCodeStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFromStorageByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).GetContractCodeStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/getContractCodeStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).GetContractCodeStorage(ctx, req.(*GetFromStorageByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_PutContractStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIntoStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).PutContractStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/putContractStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).PutContractStorage(ctx, req.(*PutIntoStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_StateCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).StateCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/stateCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).StateCheckpoint(ctx, req.(*TransactionalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_StateCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).StateCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/stateCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).StateCommit(ctx, req.(*TransactionalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_StateRevert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).StateRevert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/stateRevert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).StateRevert(ctx, req.(*TransactionalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_SetNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).SetNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/setNonce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).SetNonce(ctx, req.(*SetNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_SaveLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).SaveLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/saveLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).SaveLogs(ctx, req.(*SaveLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStorageService_DumpState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStorageServiceServer).DumpState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeStorageService/dumpState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStorageServiceServer).DumpState(ctx, req.(*DumpStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeStorageService_ServiceDesc is the grpc.ServiceDesc for NodeStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NodeStorageService",
	HandlerType: (*NodeStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAccount",
			Handler:    _NodeStorageService_GetAccount_Handler,
		},
		{
			MethodName: "createAccount",
			Handler:    _NodeStorageService_CreateAccount_Handler,
		},
		{
			MethodName: "putContractCode",
			Handler:    _NodeStorageService_PutContractCode_Handler,
		},
		{
			MethodName: "addBalance",
			Handler:    _NodeStorageService_AddBalance_Handler,
		},
		{
			MethodName: "subBalance",
			Handler:    _NodeStorageService_SubBalance_Handler,
		},
		{
			MethodName: "getContractCode",
			Handler:    _NodeStorageService_GetContractCode_Handler,
		},
		{
			MethodName: "getContractCodeStorage",
			Handler:    _NodeStorageService_GetContractCodeStorage_Handler,
		},
		{
			MethodName: "putContractStorage",
			Handler:    _NodeStorageService_PutContractStorage_Handler,
		},
		{
			MethodName: "stateCheckpoint",
			Handler:    _NodeStorageService_StateCheckpoint_Handler,
		},
		{
			MethodName: "stateCommit",
			Handler:    _NodeStorageService_StateCommit_Handler,
		},
		{
			MethodName: "stateRevert",
			Handler:    _NodeStorageService_StateRevert_Handler,
		},
		{
			MethodName: "setNonce",
			Handler:    _NodeStorageService_SetNonce_Handler,
		},
		{
			MethodName: "saveLogs",
			Handler:    _NodeStorageService_SaveLogs_Handler,
		},
		{
			MethodName: "dumpState",
			Handler:    _NodeStorageService_DumpState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}
