package io.aplfintech.luna.vm;

import io.aplfintech.luna.model.Address;
import io.aplfintech.luna.model.Hash;
import io.aplfintech.luna.utils.HexUtils;
import lombok.Getter;
import lombok.Setter;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.stream.Collectors;

/**
 * Log represents a contract log event. These events are generated by the LOG opcode
 *
 * @author andrew.zinchenko@gmail.com
 * @since 0.1
 */
public class Log {
    /**
     * Address of the contract that fired the event
     */
    @Getter
    private final Address address;
    /**
     * List of topics provided by the contract
     */
    @Getter
    private final Hash[] topics;
    /**
     * Data supplied by the contract
     * ABI-encoded event value
     */
    @Getter
    private final byte[] data;

    /**
     * The block in which the transaction was included
     */
    @Getter
    @Setter
    private BigInteger blockNumber;

    /**
     * @param address address of the contract that generated the event
     * @param topics  list of topics provided by the contract
     * @param data    date supplied by the contract
     */
    public Log(Address address, Hash[] topics, byte[] data) {
        this.address = address;
        this.topics = topics;
        this.data = data;
    }

    @Override
    public String toString() {
        return "Log{" +
            "address=" + address.hexAddress() +
            ", topics=[" + Arrays.stream(topics).map(Hash::hex).collect(Collectors.joining(",")) + ']' +
            ", data=" + HexUtils.toHex(data) +
            ", block=" + (blockNumber == null ? "unassigned" : blockNumber.toString()) +
            '}';
    }

}
